/*
 * This file is generated by jOOQ.
 */
package com.tesis.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BrandLines implements Serializable {

    private static final long serialVersionUID = 2053827023;

    private Long   id;
    private String name;
    private Long   brandId;

    public BrandLines() {}

    public BrandLines(BrandLines value) {
        this.id = value.id;
        this.name = value.name;
        this.brandId = value.brandId;
    }

    public BrandLines(
        Long   id,
        String name,
        Long   brandId
    ) {
        this.id = id;
        this.name = name;
        this.brandId = brandId;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getBrandId() {
        return this.brandId;
    }

    public void setBrandId(Long brandId) {
        this.brandId = brandId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BrandLines (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(brandId);

        sb.append(")");
        return sb.toString();
    }
}
