/*
 * This file is generated by jOOQ.
 */
package com.tesis.jooq.tables.daos;


import com.tesis.jooq.tables.AdminUsers;
import com.tesis.jooq.tables.records.AdminUsersRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AdminUsersDao extends DAOImpl<AdminUsersRecord, com.tesis.jooq.tables.pojos.AdminUsers, Long> {

    /**
     * Create a new AdminUsersDao without any configuration
     */
    public AdminUsersDao() {
        super(AdminUsers.ADMIN_USERS, com.tesis.jooq.tables.pojos.AdminUsers.class);
    }

    /**
     * Create a new AdminUsersDao with an attached configuration
     */
    public AdminUsersDao(Configuration configuration) {
        super(AdminUsers.ADMIN_USERS, com.tesis.jooq.tables.pojos.AdminUsers.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(com.tesis.jooq.tables.pojos.AdminUsers object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.tesis.jooq.tables.pojos.AdminUsers> fetchById(Long... values) {
        return fetch(AdminUsers.ADMIN_USERS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.tesis.jooq.tables.pojos.AdminUsers fetchOneById(Long value) {
        return fetchOne(AdminUsers.ADMIN_USERS.ID, value);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<com.tesis.jooq.tables.pojos.AdminUsers> fetchByStatus(String... values) {
        return fetch(AdminUsers.ADMIN_USERS.STATUS, values);
    }

    /**
     * Fetch records that have <code>deleted_at IN (values)</code>
     */
    public List<com.tesis.jooq.tables.pojos.AdminUsers> fetchByDeletedAt(Timestamp... values) {
        return fetch(AdminUsers.ADMIN_USERS.DELETED_AT, values);
    }

    /**
     * Fetch records that have <code>last_updated IN (values)</code>
     */
    public List<com.tesis.jooq.tables.pojos.AdminUsers> fetchByLastUpdated(Timestamp... values) {
        return fetch(AdminUsers.ADMIN_USERS.LAST_UPDATED, values);
    }

    /**
     * Fetch records that have <code>email IN (values)</code>
     */
    public List<com.tesis.jooq.tables.pojos.AdminUsers> fetchByEmail(String... values) {
        return fetch(AdminUsers.ADMIN_USERS.EMAIL, values);
    }

    /**
     * Fetch a unique record that has <code>email = value</code>
     */
    public com.tesis.jooq.tables.pojos.AdminUsers fetchOneByEmail(String value) {
        return fetchOne(AdminUsers.ADMIN_USERS.EMAIL, value);
    }

    /**
     * Fetch records that have <code>password IN (values)</code>
     */
    public List<com.tesis.jooq.tables.pojos.AdminUsers> fetchByPassword(String... values) {
        return fetch(AdminUsers.ADMIN_USERS.PASSWORD, values);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.tesis.jooq.tables.pojos.AdminUsers> fetchByName(String... values) {
        return fetch(AdminUsers.ADMIN_USERS.NAME, values);
    }

    /**
     * Fetch records that have <code>last_name IN (values)</code>
     */
    public List<com.tesis.jooq.tables.pojos.AdminUsers> fetchByLastName(String... values) {
        return fetch(AdminUsers.ADMIN_USERS.LAST_NAME, values);
    }

    /**
     * Fetch records that have <code>dni IN (values)</code>
     */
    public List<com.tesis.jooq.tables.pojos.AdminUsers> fetchByDni(String... values) {
        return fetch(AdminUsers.ADMIN_USERS.DNI, values);
    }

    /**
     * Fetch records that have <code>address IN (values)</code>
     */
    public List<com.tesis.jooq.tables.pojos.AdminUsers> fetchByAddress(String... values) {
        return fetch(AdminUsers.ADMIN_USERS.ADDRESS, values);
    }

    /**
     * Fetch records that have <code>phone IN (values)</code>
     */
    public List<com.tesis.jooq.tables.pojos.AdminUsers> fetchByPhone(String... values) {
        return fetch(AdminUsers.ADMIN_USERS.PHONE, values);
    }
}
