/*
 * This file is generated by jOOQ.
 */
package com.tesis.jooq.tables.daos;


import com.tesis.jooq.tables.MovementAlertsHistory;
import com.tesis.jooq.tables.records.MovementAlertsHistoryRecord;

import java.time.LocalDateTime;
import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MovementAlertsHistoryDao extends DAOImpl<MovementAlertsHistoryRecord, com.tesis.jooq.tables.pojos.MovementAlertsHistory, LocalDateTime> {

    /**
     * Create a new MovementAlertsHistoryDao without any configuration
     */
    public MovementAlertsHistoryDao() {
        super(MovementAlertsHistory.MOVEMENT_ALERTS_HISTORY, com.tesis.jooq.tables.pojos.MovementAlertsHistory.class);
    }

    /**
     * Create a new MovementAlertsHistoryDao with an attached configuration
     */
    public MovementAlertsHistoryDao(Configuration configuration) {
        super(MovementAlertsHistory.MOVEMENT_ALERTS_HISTORY, com.tesis.jooq.tables.pojos.MovementAlertsHistory.class, configuration);
    }

    @Override
    public LocalDateTime getId(com.tesis.jooq.tables.pojos.MovementAlertsHistory object) {
        return object.getTime();
    }

    /**
     * Fetch records that have <code>time BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.tesis.jooq.tables.pojos.MovementAlertsHistory> fetchRangeOfTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(MovementAlertsHistory.MOVEMENT_ALERTS_HISTORY.TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>time IN (values)</code>
     */
    public List<com.tesis.jooq.tables.pojos.MovementAlertsHistory> fetchByTime(LocalDateTime... values) {
        return fetch(MovementAlertsHistory.MOVEMENT_ALERTS_HISTORY.TIME, values);
    }

    /**
     * Fetch a unique record that has <code>time = value</code>
     */
    public com.tesis.jooq.tables.pojos.MovementAlertsHistory fetchOneByTime(LocalDateTime value) {
        return fetchOne(MovementAlertsHistory.MOVEMENT_ALERTS_HISTORY.TIME, value);
    }

    /**
     * Fetch records that have <code>alert_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.tesis.jooq.tables.pojos.MovementAlertsHistory> fetchRangeOfAlertId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(MovementAlertsHistory.MOVEMENT_ALERTS_HISTORY.ALERT_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>alert_id IN (values)</code>
     */
    public List<com.tesis.jooq.tables.pojos.MovementAlertsHistory> fetchByAlertId(Long... values) {
        return fetch(MovementAlertsHistory.MOVEMENT_ALERTS_HISTORY.ALERT_ID, values);
    }

    /**
     * Fetch records that have <code>lat BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.tesis.jooq.tables.pojos.MovementAlertsHistory> fetchRangeOfLat(Float lowerInclusive, Float upperInclusive) {
        return fetchRange(MovementAlertsHistory.MOVEMENT_ALERTS_HISTORY.LAT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>lat IN (values)</code>
     */
    public List<com.tesis.jooq.tables.pojos.MovementAlertsHistory> fetchByLat(Float... values) {
        return fetch(MovementAlertsHistory.MOVEMENT_ALERTS_HISTORY.LAT, values);
    }

    /**
     * Fetch records that have <code>lng BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.tesis.jooq.tables.pojos.MovementAlertsHistory> fetchRangeOfLng(Float lowerInclusive, Float upperInclusive) {
        return fetchRange(MovementAlertsHistory.MOVEMENT_ALERTS_HISTORY.LNG, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>lng IN (values)</code>
     */
    public List<com.tesis.jooq.tables.pojos.MovementAlertsHistory> fetchByLng(Float... values) {
        return fetch(MovementAlertsHistory.MOVEMENT_ALERTS_HISTORY.LNG, values);
    }
}
