/*
 * This file is generated by jOOQ.
 */
package com.tesis.jooq.tables.daos;


import com.tesis.jooq.tables.MovementAlerts;
import com.tesis.jooq.tables.records.MovementAlertsRecord;

import java.time.LocalDateTime;
import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MovementAlertsDao extends DAOImpl<MovementAlertsRecord, com.tesis.jooq.tables.pojos.MovementAlerts, Long> {

    /**
     * Create a new MovementAlertsDao without any configuration
     */
    public MovementAlertsDao() {
        super(MovementAlerts.MOVEMENT_ALERTS, com.tesis.jooq.tables.pojos.MovementAlerts.class);
    }

    /**
     * Create a new MovementAlertsDao with an attached configuration
     */
    public MovementAlertsDao(Configuration configuration) {
        super(MovementAlerts.MOVEMENT_ALERTS, com.tesis.jooq.tables.pojos.MovementAlerts.class, configuration);
    }

    @Override
    public Long getId(com.tesis.jooq.tables.pojos.MovementAlerts object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.tesis.jooq.tables.pojos.MovementAlerts> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(MovementAlerts.MOVEMENT_ALERTS.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.tesis.jooq.tables.pojos.MovementAlerts> fetchById(Long... values) {
        return fetch(MovementAlerts.MOVEMENT_ALERTS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.tesis.jooq.tables.pojos.MovementAlerts fetchOneById(Long value) {
        return fetchOne(MovementAlerts.MOVEMENT_ALERTS.ID, value);
    }

    /**
     * Fetch records that have <code>active BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.tesis.jooq.tables.pojos.MovementAlerts> fetchRangeOfActive(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(MovementAlerts.MOVEMENT_ALERTS.ACTIVE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>active IN (values)</code>
     */
    public List<com.tesis.jooq.tables.pojos.MovementAlerts> fetchByActive(Boolean... values) {
        return fetch(MovementAlerts.MOVEMENT_ALERTS.ACTIVE, values);
    }

    /**
     * Fetch records that have <code>lat BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.tesis.jooq.tables.pojos.MovementAlerts> fetchRangeOfLat(Float lowerInclusive, Float upperInclusive) {
        return fetchRange(MovementAlerts.MOVEMENT_ALERTS.LAT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>lat IN (values)</code>
     */
    public List<com.tesis.jooq.tables.pojos.MovementAlerts> fetchByLat(Float... values) {
        return fetch(MovementAlerts.MOVEMENT_ALERTS.LAT, values);
    }

    /**
     * Fetch records that have <code>lng BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.tesis.jooq.tables.pojos.MovementAlerts> fetchRangeOfLng(Float lowerInclusive, Float upperInclusive) {
        return fetchRange(MovementAlerts.MOVEMENT_ALERTS.LNG, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>lng IN (values)</code>
     */
    public List<com.tesis.jooq.tables.pojos.MovementAlerts> fetchByLng(Float... values) {
        return fetch(MovementAlerts.MOVEMENT_ALERTS.LNG, values);
    }

    /**
     * Fetch records that have <code>device_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.tesis.jooq.tables.pojos.MovementAlerts> fetchRangeOfDeviceId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(MovementAlerts.MOVEMENT_ALERTS.DEVICE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>device_id IN (values)</code>
     */
    public List<com.tesis.jooq.tables.pojos.MovementAlerts> fetchByDeviceId(Long... values) {
        return fetch(MovementAlerts.MOVEMENT_ALERTS.DEVICE_ID, values);
    }

    /**
     * Fetch a unique record that has <code>device_id = value</code>
     */
    public com.tesis.jooq.tables.pojos.MovementAlerts fetchOneByDeviceId(Long value) {
        return fetchOne(MovementAlerts.MOVEMENT_ALERTS.DEVICE_ID, value);
    }

    /**
     * Fetch records that have <code>created_at BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.tesis.jooq.tables.pojos.MovementAlerts> fetchRangeOfCreatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(MovementAlerts.MOVEMENT_ALERTS.CREATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<com.tesis.jooq.tables.pojos.MovementAlerts> fetchByCreatedAt(LocalDateTime... values) {
        return fetch(MovementAlerts.MOVEMENT_ALERTS.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>updated_at BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.tesis.jooq.tables.pojos.MovementAlerts> fetchRangeOfUpdatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(MovementAlerts.MOVEMENT_ALERTS.UPDATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>updated_at IN (values)</code>
     */
    public List<com.tesis.jooq.tables.pojos.MovementAlerts> fetchByUpdatedAt(LocalDateTime... values) {
        return fetch(MovementAlerts.MOVEMENT_ALERTS.UPDATED_AT, values);
    }

    /**
     * Fetch records that have <code>activated_at BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.tesis.jooq.tables.pojos.MovementAlerts> fetchRangeOfActivatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(MovementAlerts.MOVEMENT_ALERTS.ACTIVATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>activated_at IN (values)</code>
     */
    public List<com.tesis.jooq.tables.pojos.MovementAlerts> fetchByActivatedAt(LocalDateTime... values) {
        return fetch(MovementAlerts.MOVEMENT_ALERTS.ACTIVATED_AT, values);
    }

    /**
     * Fetch records that have <code>last_fired BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.tesis.jooq.tables.pojos.MovementAlerts> fetchRangeOfLastFired(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(MovementAlerts.MOVEMENT_ALERTS.LAST_FIRED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>last_fired IN (values)</code>
     */
    public List<com.tesis.jooq.tables.pojos.MovementAlerts> fetchByLastFired(LocalDateTime... values) {
        return fetch(MovementAlerts.MOVEMENT_ALERTS.LAST_FIRED, values);
    }
}
