/*
 * This file is generated by jOOQ.
 */
package com.tesis.jooq.tables.daos;


import com.tesis.jooq.tables.SpeedAlerts;
import com.tesis.jooq.tables.records.SpeedAlertsRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpeedAlertsDao extends DAOImpl<SpeedAlertsRecord, com.tesis.jooq.tables.pojos.SpeedAlerts, Long> {

    /**
     * Create a new SpeedAlertsDao without any configuration
     */
    public SpeedAlertsDao() {
        super(SpeedAlerts.SPEED_ALERTS, com.tesis.jooq.tables.pojos.SpeedAlerts.class);
    }

    /**
     * Create a new SpeedAlertsDao with an attached configuration
     */
    public SpeedAlertsDao(Configuration configuration) {
        super(SpeedAlerts.SPEED_ALERTS, com.tesis.jooq.tables.pojos.SpeedAlerts.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(com.tesis.jooq.tables.pojos.SpeedAlerts object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.tesis.jooq.tables.pojos.SpeedAlerts> fetchById(Long... values) {
        return fetch(SpeedAlerts.SPEED_ALERTS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.tesis.jooq.tables.pojos.SpeedAlerts fetchOneById(Long value) {
        return fetchOne(SpeedAlerts.SPEED_ALERTS.ID, value);
    }

    /**
     * Fetch records that have <code>active IN (values)</code>
     */
    public List<com.tesis.jooq.tables.pojos.SpeedAlerts> fetchByActive(Boolean... values) {
        return fetch(SpeedAlerts.SPEED_ALERTS.ACTIVE, values);
    }

    /**
     * Fetch records that have <code>speed IN (values)</code>
     */
    public List<com.tesis.jooq.tables.pojos.SpeedAlerts> fetchBySpeed(Float... values) {
        return fetch(SpeedAlerts.SPEED_ALERTS.SPEED, values);
    }

    /**
     * Fetch records that have <code>device_id IN (values)</code>
     */
    public List<com.tesis.jooq.tables.pojos.SpeedAlerts> fetchByDeviceId(Long... values) {
        return fetch(SpeedAlerts.SPEED_ALERTS.DEVICE_ID, values);
    }

    /**
     * Fetch a unique record that has <code>device_id = value</code>
     */
    public com.tesis.jooq.tables.pojos.SpeedAlerts fetchOneByDeviceId(Long value) {
        return fetchOne(SpeedAlerts.SPEED_ALERTS.DEVICE_ID, value);
    }
}
