/*
 * This file is generated by jOOQ.
 */
package com.tesis.jooq.tables.daos;


import com.tesis.jooq.tables.SpeedAlertsHistory;
import com.tesis.jooq.tables.records.SpeedAlertsHistoryRecord;

import java.time.LocalDateTime;
import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpeedAlertsHistoryDao extends DAOImpl<SpeedAlertsHistoryRecord, com.tesis.jooq.tables.pojos.SpeedAlertsHistory, LocalDateTime> {

    /**
     * Create a new SpeedAlertsHistoryDao without any configuration
     */
    public SpeedAlertsHistoryDao() {
        super(SpeedAlertsHistory.SPEED_ALERTS_HISTORY, com.tesis.jooq.tables.pojos.SpeedAlertsHistory.class);
    }

    /**
     * Create a new SpeedAlertsHistoryDao with an attached configuration
     */
    public SpeedAlertsHistoryDao(Configuration configuration) {
        super(SpeedAlertsHistory.SPEED_ALERTS_HISTORY, com.tesis.jooq.tables.pojos.SpeedAlertsHistory.class, configuration);
    }

    @Override
    public LocalDateTime getId(com.tesis.jooq.tables.pojos.SpeedAlertsHistory object) {
        return object.getTime();
    }

    /**
     * Fetch records that have <code>time BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.tesis.jooq.tables.pojos.SpeedAlertsHistory> fetchRangeOfTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(SpeedAlertsHistory.SPEED_ALERTS_HISTORY.TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>time IN (values)</code>
     */
    public List<com.tesis.jooq.tables.pojos.SpeedAlertsHistory> fetchByTime(LocalDateTime... values) {
        return fetch(SpeedAlertsHistory.SPEED_ALERTS_HISTORY.TIME, values);
    }

    /**
     * Fetch a unique record that has <code>time = value</code>
     */
    public com.tesis.jooq.tables.pojos.SpeedAlertsHistory fetchOneByTime(LocalDateTime value) {
        return fetchOne(SpeedAlertsHistory.SPEED_ALERTS_HISTORY.TIME, value);
    }

    /**
     * Fetch records that have <code>alert_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.tesis.jooq.tables.pojos.SpeedAlertsHistory> fetchRangeOfAlertId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(SpeedAlertsHistory.SPEED_ALERTS_HISTORY.ALERT_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>alert_id IN (values)</code>
     */
    public List<com.tesis.jooq.tables.pojos.SpeedAlertsHistory> fetchByAlertId(Long... values) {
        return fetch(SpeedAlertsHistory.SPEED_ALERTS_HISTORY.ALERT_ID, values);
    }

    /**
     * Fetch records that have <code>speed BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.tesis.jooq.tables.pojos.SpeedAlertsHistory> fetchRangeOfSpeed(Float lowerInclusive, Float upperInclusive) {
        return fetchRange(SpeedAlertsHistory.SPEED_ALERTS_HISTORY.SPEED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>speed IN (values)</code>
     */
    public List<com.tesis.jooq.tables.pojos.SpeedAlertsHistory> fetchBySpeed(Float... values) {
        return fetch(SpeedAlertsHistory.SPEED_ALERTS_HISTORY.SPEED, values);
    }
}
