/*
 * This file is generated by jOOQ.
 */
package com.tesis.jooq.tables.records;


import com.tesis.jooq.tables.MovementAlerts;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MovementAlertsRecord extends UpdatableRecordImpl<MovementAlertsRecord> implements Record8<Long, Boolean, Float, Float, Long, Timestamp, Timestamp, Timestamp> {

    private static final long serialVersionUID = -1972700997;

    /**
     * Setter for <code>public.movement_alerts.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.movement_alerts.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.movement_alerts.active</code>.
     */
    public void setActive(Boolean value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.movement_alerts.active</code>.
     */
    public Boolean getActive() {
        return (Boolean) get(1);
    }

    /**
     * Setter for <code>public.movement_alerts.lat</code>.
     */
    public void setLat(Float value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.movement_alerts.lat</code>.
     */
    public Float getLat() {
        return (Float) get(2);
    }

    /**
     * Setter for <code>public.movement_alerts.lng</code>.
     */
    public void setLng(Float value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.movement_alerts.lng</code>.
     */
    public Float getLng() {
        return (Float) get(3);
    }

    /**
     * Setter for <code>public.movement_alerts.device_id</code>.
     */
    public void setDeviceId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.movement_alerts.device_id</code>.
     */
    public Long getDeviceId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.movement_alerts.created_at</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.movement_alerts.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>public.movement_alerts.updated_at</code>.
     */
    public void setUpdatedAt(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.movement_alerts.updated_at</code>.
     */
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>public.movement_alerts.activated_at</code>.
     */
    public void setActivatedAt(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.movement_alerts.activated_at</code>.
     */
    public Timestamp getActivatedAt() {
        return (Timestamp) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, Boolean, Float, Float, Long, Timestamp, Timestamp, Timestamp> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, Boolean, Float, Float, Long, Timestamp, Timestamp, Timestamp> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return MovementAlerts.MOVEMENT_ALERTS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field2() {
        return MovementAlerts.MOVEMENT_ALERTS.ACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Float> field3() {
        return MovementAlerts.MOVEMENT_ALERTS.LAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Float> field4() {
        return MovementAlerts.MOVEMENT_ALERTS.LNG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return MovementAlerts.MOVEMENT_ALERTS.DEVICE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return MovementAlerts.MOVEMENT_ALERTS.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return MovementAlerts.MOVEMENT_ALERTS.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return MovementAlerts.MOVEMENT_ALERTS.ACTIVATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component2() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float component3() {
        return getLat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float component4() {
        return getLng();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getDeviceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getActivatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value2() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float value3() {
        return getLat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float value4() {
        return getLng();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getDeviceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getActivatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MovementAlertsRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MovementAlertsRecord value2(Boolean value) {
        setActive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MovementAlertsRecord value3(Float value) {
        setLat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MovementAlertsRecord value4(Float value) {
        setLng(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MovementAlertsRecord value5(Long value) {
        setDeviceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MovementAlertsRecord value6(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MovementAlertsRecord value7(Timestamp value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MovementAlertsRecord value8(Timestamp value) {
        setActivatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MovementAlertsRecord values(Long value1, Boolean value2, Float value3, Float value4, Long value5, Timestamp value6, Timestamp value7, Timestamp value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MovementAlertsRecord
     */
    public MovementAlertsRecord() {
        super(MovementAlerts.MOVEMENT_ALERTS);
    }

    /**
     * Create a detached, initialised MovementAlertsRecord
     */
    public MovementAlertsRecord(Long id, Boolean active, Float lat, Float lng, Long deviceId, Timestamp createdAt, Timestamp updatedAt, Timestamp activatedAt) {
        super(MovementAlerts.MOVEMENT_ALERTS);

        set(0, id);
        set(1, active);
        set(2, lat);
        set(3, lng);
        set(4, deviceId);
        set(5, createdAt);
        set(6, updatedAt);
        set(7, activatedAt);
    }
}
