/*
 * This file is generated by jOOQ.
 */
package com.tesis.jooq.tables.records;


import com.tesis.jooq.tables.SpeedAlertsHistory;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpeedAlertsHistoryRecord extends UpdatableRecordImpl<SpeedAlertsHistoryRecord> implements Record3<Timestamp, Long, Float> {

    private static final long serialVersionUID = 1161891747;

    /**
     * Setter for <code>public.speed_alerts_history.time</code>.
     */
    public void setTime(Timestamp value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.speed_alerts_history.time</code>.
     */
    public Timestamp getTime() {
        return (Timestamp) get(0);
    }

    /**
     * Setter for <code>public.speed_alerts_history.alert_id</code>.
     */
    public void setAlertId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.speed_alerts_history.alert_id</code>.
     */
    public Long getAlertId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.speed_alerts_history.speed</code>.
     */
    public void setSpeed(Float value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.speed_alerts_history.speed</code>.
     */
    public Float getSpeed() {
        return (Float) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Timestamp> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Timestamp, Long, Float> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Timestamp, Long, Float> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field1() {
        return SpeedAlertsHistory.SPEED_ALERTS_HISTORY.TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return SpeedAlertsHistory.SPEED_ALERTS_HISTORY.ALERT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Float> field3() {
        return SpeedAlertsHistory.SPEED_ALERTS_HISTORY.SPEED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component1() {
        return getTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getAlertId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float component3() {
        return getSpeed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value1() {
        return getTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getAlertId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float value3() {
        return getSpeed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpeedAlertsHistoryRecord value1(Timestamp value) {
        setTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpeedAlertsHistoryRecord value2(Long value) {
        setAlertId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpeedAlertsHistoryRecord value3(Float value) {
        setSpeed(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpeedAlertsHistoryRecord values(Timestamp value1, Long value2, Float value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SpeedAlertsHistoryRecord
     */
    public SpeedAlertsHistoryRecord() {
        super(SpeedAlertsHistory.SPEED_ALERTS_HISTORY);
    }

    /**
     * Create a detached, initialised SpeedAlertsHistoryRecord
     */
    public SpeedAlertsHistoryRecord(Timestamp time, Long alertId, Float speed) {
        super(SpeedAlertsHistory.SPEED_ALERTS_HISTORY);

        set(0, time);
        set(1, alertId);
        set(2, speed);
    }
}
