/*
 * This file is generated by jOOQ.
 */
package com.tesis.jooq.tables.daos;


import com.tesis.jooq.tables.MovementAlertsHistory;
import com.tesis.jooq.tables.records.MovementAlertsHistoryRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MovementAlertsHistoryDao extends DAOImpl<MovementAlertsHistoryRecord, com.tesis.jooq.tables.pojos.MovementAlertsHistory, Timestamp> {

    /**
     * Create a new MovementAlertsHistoryDao without any configuration
     */
    public MovementAlertsHistoryDao() {
        super(MovementAlertsHistory.MOVEMENT_ALERTS_HISTORY, com.tesis.jooq.tables.pojos.MovementAlertsHistory.class);
    }

    /**
     * Create a new MovementAlertsHistoryDao with an attached configuration
     */
    public MovementAlertsHistoryDao(Configuration configuration) {
        super(MovementAlertsHistory.MOVEMENT_ALERTS_HISTORY, com.tesis.jooq.tables.pojos.MovementAlertsHistory.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Timestamp getId(com.tesis.jooq.tables.pojos.MovementAlertsHistory object) {
        return object.getTime();
    }

    /**
     * Fetch records that have <code>time IN (values)</code>
     */
    public List<com.tesis.jooq.tables.pojos.MovementAlertsHistory> fetchByTime(Timestamp... values) {
        return fetch(MovementAlertsHistory.MOVEMENT_ALERTS_HISTORY.TIME, values);
    }

    /**
     * Fetch a unique record that has <code>time = value</code>
     */
    public com.tesis.jooq.tables.pojos.MovementAlertsHistory fetchOneByTime(Timestamp value) {
        return fetchOne(MovementAlertsHistory.MOVEMENT_ALERTS_HISTORY.TIME, value);
    }

    /**
     * Fetch records that have <code>alert_id IN (values)</code>
     */
    public List<com.tesis.jooq.tables.pojos.MovementAlertsHistory> fetchByAlertId(Long... values) {
        return fetch(MovementAlertsHistory.MOVEMENT_ALERTS_HISTORY.ALERT_ID, values);
    }

    /**
     * Fetch records that have <code>lat IN (values)</code>
     */
    public List<com.tesis.jooq.tables.pojos.MovementAlertsHistory> fetchByLat(Float... values) {
        return fetch(MovementAlertsHistory.MOVEMENT_ALERTS_HISTORY.LAT, values);
    }

    /**
     * Fetch records that have <code>lng IN (values)</code>
     */
    public List<com.tesis.jooq.tables.pojos.MovementAlertsHistory> fetchByLng(Float... values) {
        return fetch(MovementAlertsHistory.MOVEMENT_ALERTS_HISTORY.LNG, values);
    }
}
