/*
 * This file is generated by jOOQ.
 */
package com.tesis.jooq.tables.daos;


import com.tesis.jooq.tables.RecoveryTokens;
import com.tesis.jooq.tables.records.RecoveryTokensRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RecoveryTokensDao extends DAOImpl<RecoveryTokensRecord, com.tesis.jooq.tables.pojos.RecoveryTokens, Long> {

    /**
     * Create a new RecoveryTokensDao without any configuration
     */
    public RecoveryTokensDao() {
        super(RecoveryTokens.RECOVERY_TOKENS, com.tesis.jooq.tables.pojos.RecoveryTokens.class);
    }

    /**
     * Create a new RecoveryTokensDao with an attached configuration
     */
    public RecoveryTokensDao(Configuration configuration) {
        super(RecoveryTokens.RECOVERY_TOKENS, com.tesis.jooq.tables.pojos.RecoveryTokens.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(com.tesis.jooq.tables.pojos.RecoveryTokens object) {
        return object.getUserId();
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<com.tesis.jooq.tables.pojos.RecoveryTokens> fetchByUserId(Long... values) {
        return fetch(RecoveryTokens.RECOVERY_TOKENS.USER_ID, values);
    }

    /**
     * Fetch a unique record that has <code>user_id = value</code>
     */
    public com.tesis.jooq.tables.pojos.RecoveryTokens fetchOneByUserId(Long value) {
        return fetchOne(RecoveryTokens.RECOVERY_TOKENS.USER_ID, value);
    }

    /**
     * Fetch records that have <code>token IN (values)</code>
     */
    public List<com.tesis.jooq.tables.pojos.RecoveryTokens> fetchByToken(String... values) {
        return fetch(RecoveryTokens.RECOVERY_TOKENS.TOKEN, values);
    }

    /**
     * Fetch a unique record that has <code>token = value</code>
     */
    public com.tesis.jooq.tables.pojos.RecoveryTokens fetchOneByToken(String value) {
        return fetchOne(RecoveryTokens.RECOVERY_TOKENS.TOKEN, value);
    }

    /**
     * Fetch records that have <code>expiration_date IN (values)</code>
     */
    public List<com.tesis.jooq.tables.pojos.RecoveryTokens> fetchByExpirationDate(Timestamp... values) {
        return fetch(RecoveryTokens.RECOVERY_TOKENS.EXPIRATION_DATE, values);
    }
}
