package com.tesis.enums;

public enum Privileges {
    CREATE_CLIENT,
    GET_CLIENT,
    UPDATE_CLIENT,
    DELETE_CLIENT,

    CREATE_VEHICLE,
    GET_VEHICLE,
    UPDATE_VEHICLE,
    DELETE_VEHICLE,

    GET_TRACKING,
    CREATE_TRACKING,

    CREATE_ALERT,
    GET_ALERT,
    UPDATE_ALERT,
    DELETE_ALERT,
    SEND_ALERT,

    CREATE_ALERT_HISTORY,
    GET_ALERT_HISTORY,

    CREATE_DEVICE,
    GET_DEVICE,
    UPDATE_DEVICE,
    DELETE_DEVICE,

    GET_BRAND,
    CREATE_BRAND,
    UPDATE_BRAND,
    DELETE_BRAND,

    GET_BRAND_LINE,
    CREATE_BRAND_LINE,
    UPDATE_BRAND_LINE,
    DELETE_BRAND_LINE;
}
