/*
 * This file is generated by jOOQ.
 */
package com.tesis.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccessTokens implements Serializable {

    private static final long serialVersionUID = 50393379;

    private Long   id;
    private String token;

    public AccessTokens() {}

    public AccessTokens(AccessTokens value) {
        this.id = value.id;
        this.token = value.token;
    }

    public AccessTokens(
        Long   id,
        String token
    ) {
        this.id = id;
        this.token = token;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getToken() {
        return this.token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AccessTokens (");

        sb.append(id);
        sb.append(", ").append(token);

        sb.append(")");
        return sb.toString();
    }
}
