/*
 * This file is generated by jOOQ.
 */
package com.tesis.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AdminRecoveryTokens implements Serializable {

    private static final long serialVersionUID = -2128464473;

    private Long      userId;
    private String    token;
    private Timestamp expirationDate;

    public AdminRecoveryTokens() {}

    public AdminRecoveryTokens(AdminRecoveryTokens value) {
        this.userId = value.userId;
        this.token = value.token;
        this.expirationDate = value.expirationDate;
    }

    public AdminRecoveryTokens(
        Long      userId,
        String    token,
        Timestamp expirationDate
    ) {
        this.userId = userId;
        this.token = token;
        this.expirationDate = expirationDate;
    }

    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getToken() {
        return this.token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public Timestamp getExpirationDate() {
        return this.expirationDate;
    }

    public void setExpirationDate(Timestamp expirationDate) {
        this.expirationDate = expirationDate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AdminRecoveryTokens (");

        sb.append(userId);
        sb.append(", ").append(token);
        sb.append(", ").append(expirationDate);

        sb.append(")");
        return sb.toString();
    }
}
