/*
 * This file is generated by jOOQ.
 */
package com.tesis.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AdminAccessTokens implements Serializable {

    private static final long serialVersionUID = 523687226;

    private Long   userId;
    private String token;

    public AdminAccessTokens() {}

    public AdminAccessTokens(AdminAccessTokens value) {
        this.userId = value.userId;
        this.token = value.token;
    }

    public AdminAccessTokens(
        Long   userId,
        String token
    ) {
        this.userId = userId;
        this.token = token;
    }

    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getToken() {
        return this.token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AdminAccessTokens (");

        sb.append(userId);
        sb.append(", ").append(token);

        sb.append(")");
        return sb.toString();
    }
}
