/*
 * This file is generated by jOOQ.
 */
package com.tesis.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Devices implements Serializable {

    private static final long serialVersionUID = -1976084961;

    private Long          id;
    private Long          physicalId;
    private LocalDateTime deletedAt;
    private LocalDateTime lastUpdated;
    private String        model;
    private String        softwareVersion;
    private String        status;

    public Devices() {}

    public Devices(Devices value) {
        this.id = value.id;
        this.physicalId = value.physicalId;
        this.deletedAt = value.deletedAt;
        this.lastUpdated = value.lastUpdated;
        this.model = value.model;
        this.softwareVersion = value.softwareVersion;
        this.status = value.status;
    }

    public Devices(
        Long          id,
        Long          physicalId,
        LocalDateTime deletedAt,
        LocalDateTime lastUpdated,
        String        model,
        String        softwareVersion,
        String        status
    ) {
        this.id = id;
        this.physicalId = physicalId;
        this.deletedAt = deletedAt;
        this.lastUpdated = lastUpdated;
        this.model = model;
        this.softwareVersion = softwareVersion;
        this.status = status;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getPhysicalId() {
        return this.physicalId;
    }

    public void setPhysicalId(Long physicalId) {
        this.physicalId = physicalId;
    }

    public LocalDateTime getDeletedAt() {
        return this.deletedAt;
    }

    public void setDeletedAt(LocalDateTime deletedAt) {
        this.deletedAt = deletedAt;
    }

    public LocalDateTime getLastUpdated() {
        return this.lastUpdated;
    }

    public void setLastUpdated(LocalDateTime lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    public String getModel() {
        return this.model;
    }

    public void setModel(String model) {
        this.model = model;
    }

    public String getSoftwareVersion() {
        return this.softwareVersion;
    }

    public void setSoftwareVersion(String softwareVersion) {
        this.softwareVersion = softwareVersion;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Devices (");

        sb.append(id);
        sb.append(", ").append(physicalId);
        sb.append(", ").append(deletedAt);
        sb.append(", ").append(lastUpdated);
        sb.append(", ").append(model);
        sb.append(", ").append(softwareVersion);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }
}
