/*
 * This file is generated by jOOQ.
 */
package com.tesis.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Devices implements Serializable {

    private static final long serialVersionUID = 363944725;

    private Long   id;
    private Long   userId;
    private Long   vehicleId;
    private String model;
    private String softwareVersion;

    public Devices() {}

    public Devices(Devices value) {
        this.id = value.id;
        this.userId = value.userId;
        this.vehicleId = value.vehicleId;
        this.model = value.model;
        this.softwareVersion = value.softwareVersion;
    }

    public Devices(
        Long   id,
        Long   userId,
        Long   vehicleId,
        String model,
        String softwareVersion
    ) {
        this.id = id;
        this.userId = userId;
        this.vehicleId = vehicleId;
        this.model = model;
        this.softwareVersion = softwareVersion;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Long getVehicleId() {
        return this.vehicleId;
    }

    public void setVehicleId(Long vehicleId) {
        this.vehicleId = vehicleId;
    }

    public String getModel() {
        return this.model;
    }

    public void setModel(String model) {
        this.model = model;
    }

    public String getSoftwareVersion() {
        return this.softwareVersion;
    }

    public void setSoftwareVersion(String softwareVersion) {
        this.softwareVersion = softwareVersion;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Devices (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(vehicleId);
        sb.append(", ").append(model);
        sb.append(", ").append(softwareVersion);

        sb.append(")");
        return sb.toString();
    }
}
