/*
 * This file is generated by jOOQ.
 */
package com.tesis.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MovementAlerts implements Serializable {

    private static final long serialVersionUID = 219932141;

    private Long    id;
    private Boolean active;
    private Float   lat;
    private Float   lng;
    private Long    deviceId;

    public MovementAlerts() {}

    public MovementAlerts(MovementAlerts value) {
        this.id = value.id;
        this.active = value.active;
        this.lat = value.lat;
        this.lng = value.lng;
        this.deviceId = value.deviceId;
    }

    public MovementAlerts(
        Long    id,
        Boolean active,
        Float   lat,
        Float   lng,
        Long    deviceId
    ) {
        this.id = id;
        this.active = active;
        this.lat = lat;
        this.lng = lng;
        this.deviceId = deviceId;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Boolean getActive() {
        return this.active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }

    public Float getLat() {
        return this.lat;
    }

    public void setLat(Float lat) {
        this.lat = lat;
    }

    public Float getLng() {
        return this.lng;
    }

    public void setLng(Float lng) {
        this.lng = lng;
    }

    public Long getDeviceId() {
        return this.deviceId;
    }

    public void setDeviceId(Long deviceId) {
        this.deviceId = deviceId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MovementAlerts (");

        sb.append(id);
        sb.append(", ").append(active);
        sb.append(", ").append(lat);
        sb.append(", ").append(lng);
        sb.append(", ").append(deviceId);

        sb.append(")");
        return sb.toString();
    }
}
