/*
 * This file is generated by jOOQ.
 */
package com.tesis.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpeedAlerts implements Serializable {

    private static final long serialVersionUID = 2072940121;

    private Long          id;
    private Boolean       active;
    private Float         speed;
    private Long          deviceId;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
    private LocalDateTime activatedAt;
    private LocalDateTime lastFired;

    public SpeedAlerts() {}

    public SpeedAlerts(SpeedAlerts value) {
        this.id = value.id;
        this.active = value.active;
        this.speed = value.speed;
        this.deviceId = value.deviceId;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
        this.activatedAt = value.activatedAt;
        this.lastFired = value.lastFired;
    }

    public SpeedAlerts(
        Long          id,
        Boolean       active,
        Float         speed,
        Long          deviceId,
        LocalDateTime createdAt,
        LocalDateTime updatedAt,
        LocalDateTime activatedAt,
        LocalDateTime lastFired
    ) {
        this.id = id;
        this.active = active;
        this.speed = speed;
        this.deviceId = deviceId;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.activatedAt = activatedAt;
        this.lastFired = lastFired;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Boolean getActive() {
        return this.active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }

    public Float getSpeed() {
        return this.speed;
    }

    public void setSpeed(Float speed) {
        this.speed = speed;
    }

    public Long getDeviceId() {
        return this.deviceId;
    }

    public void setDeviceId(Long deviceId) {
        this.deviceId = deviceId;
    }

    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    public LocalDateTime getActivatedAt() {
        return this.activatedAt;
    }

    public void setActivatedAt(LocalDateTime activatedAt) {
        this.activatedAt = activatedAt;
    }

    public LocalDateTime getLastFired() {
        return this.lastFired;
    }

    public void setLastFired(LocalDateTime lastFired) {
        this.lastFired = lastFired;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SpeedAlerts (");

        sb.append(id);
        sb.append(", ").append(active);
        sb.append(", ").append(speed);
        sb.append(", ").append(deviceId);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);
        sb.append(", ").append(activatedAt);
        sb.append(", ").append(lastFired);

        sb.append(")");
        return sb.toString();
    }
}
