/*
 * This file is generated by jOOQ.
 */
package com.tesis.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users implements Serializable {

    private static final long serialVersionUID = 1292202733;

    private Long      id;
    private Timestamp deletedAt;
    private Timestamp lastUpdated;
    private String    userName;
    private String    password;
    private String    name;
    private String    lastName;
    private String    dni;
    private String    address;
    private String    phone;
    private String    email;

    public Users() {}

    public Users(Users value) {
        this.id = value.id;
        this.deletedAt = value.deletedAt;
        this.lastUpdated = value.lastUpdated;
        this.userName = value.userName;
        this.password = value.password;
        this.name = value.name;
        this.lastName = value.lastName;
        this.dni = value.dni;
        this.address = value.address;
        this.phone = value.phone;
        this.email = value.email;
    }

    public Users(
        Long      id,
        Timestamp deletedAt,
        Timestamp lastUpdated,
        String    userName,
        String    password,
        String    name,
        String    lastName,
        String    dni,
        String    address,
        String    phone,
        String    email
    ) {
        this.id = id;
        this.deletedAt = deletedAt;
        this.lastUpdated = lastUpdated;
        this.userName = userName;
        this.password = password;
        this.name = name;
        this.lastName = lastName;
        this.dni = dni;
        this.address = address;
        this.phone = phone;
        this.email = email;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Timestamp getDeletedAt() {
        return this.deletedAt;
    }

    public void setDeletedAt(Timestamp deletedAt) {
        this.deletedAt = deletedAt;
    }

    public Timestamp getLastUpdated() {
        return this.lastUpdated;
    }

    public void setLastUpdated(Timestamp lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getDni() {
        return this.dni;
    }

    public void setDni(String dni) {
        this.dni = dni;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Users (");

        sb.append(id);
        sb.append(", ").append(deletedAt);
        sb.append(", ").append(lastUpdated);
        sb.append(", ").append(userName);
        sb.append(", ").append(password);
        sb.append(", ").append(name);
        sb.append(", ").append(lastName);
        sb.append(", ").append(dni);
        sb.append(", ").append(address);
        sb.append(", ").append(phone);
        sb.append(", ").append(email);

        sb.append(")");
        return sb.toString();
    }
}
