/*
 * This file is generated by jOOQ.
 */
package com.tesis.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Vehicles implements Serializable {

    private static final long serialVersionUID = -296459914;

    private Long id;

    public Vehicles() {}

    public Vehicles(Vehicles value) {
        this.id = value.id;
    }

    public Vehicles(
        Long id
    ) {
        this.id = id;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Vehicles (");

        sb.append(id);

        sb.append(")");
        return sb.toString();
    }
}
