/*
 * This file is generated by jOOQ.
 */
package com.tesis.jooq.tables.records;


import com.tesis.jooq.tables.Devices;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DevicesRecord extends UpdatableRecordImpl<DevicesRecord> implements Record7<Long, Long, LocalDateTime, LocalDateTime, String, String, String> {

    private static final long serialVersionUID = -486970697;

    /**
     * Setter for <code>public.devices.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.devices.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.devices.physical_id</code>.
     */
    public void setPhysicalId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.devices.physical_id</code>.
     */
    public Long getPhysicalId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.devices.deleted_at</code>.
     */
    public void setDeletedAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.devices.deleted_at</code>.
     */
    public LocalDateTime getDeletedAt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.devices.last_updated</code>.
     */
    public void setLastUpdated(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.devices.last_updated</code>.
     */
    public LocalDateTime getLastUpdated() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.devices.model</code>.
     */
    public void setModel(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.devices.model</code>.
     */
    public String getModel() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.devices.software_version</code>.
     */
    public void setSoftwareVersion(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.devices.software_version</code>.
     */
    public String getSoftwareVersion() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.devices.status</code>.
     */
    public void setStatus(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.devices.status</code>.
     */
    public String getStatus() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, Long, LocalDateTime, LocalDateTime, String, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, Long, LocalDateTime, LocalDateTime, String, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Devices.DEVICES.ID;
    }

    @Override
    public Field<Long> field2() {
        return Devices.DEVICES.PHYSICAL_ID;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return Devices.DEVICES.DELETED_AT;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return Devices.DEVICES.LAST_UPDATED;
    }

    @Override
    public Field<String> field5() {
        return Devices.DEVICES.MODEL;
    }

    @Override
    public Field<String> field6() {
        return Devices.DEVICES.SOFTWARE_VERSION;
    }

    @Override
    public Field<String> field7() {
        return Devices.DEVICES.STATUS;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getPhysicalId();
    }

    @Override
    public LocalDateTime component3() {
        return getDeletedAt();
    }

    @Override
    public LocalDateTime component4() {
        return getLastUpdated();
    }

    @Override
    public String component5() {
        return getModel();
    }

    @Override
    public String component6() {
        return getSoftwareVersion();
    }

    @Override
    public String component7() {
        return getStatus();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getPhysicalId();
    }

    @Override
    public LocalDateTime value3() {
        return getDeletedAt();
    }

    @Override
    public LocalDateTime value4() {
        return getLastUpdated();
    }

    @Override
    public String value5() {
        return getModel();
    }

    @Override
    public String value6() {
        return getSoftwareVersion();
    }

    @Override
    public String value7() {
        return getStatus();
    }

    @Override
    public DevicesRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public DevicesRecord value2(Long value) {
        setPhysicalId(value);
        return this;
    }

    @Override
    public DevicesRecord value3(LocalDateTime value) {
        setDeletedAt(value);
        return this;
    }

    @Override
    public DevicesRecord value4(LocalDateTime value) {
        setLastUpdated(value);
        return this;
    }

    @Override
    public DevicesRecord value5(String value) {
        setModel(value);
        return this;
    }

    @Override
    public DevicesRecord value6(String value) {
        setSoftwareVersion(value);
        return this;
    }

    @Override
    public DevicesRecord value7(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public DevicesRecord values(Long value1, Long value2, LocalDateTime value3, LocalDateTime value4, String value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DevicesRecord
     */
    public DevicesRecord() {
        super(Devices.DEVICES);
    }

    /**
     * Create a detached, initialised DevicesRecord
     */
    public DevicesRecord(Long id, Long physicalId, LocalDateTime deletedAt, LocalDateTime lastUpdated, String model, String softwareVersion, String status) {
        super(Devices.DEVICES);

        set(0, id);
        set(1, physicalId);
        set(2, deletedAt);
        set(3, lastUpdated);
        set(4, model);
        set(5, softwareVersion);
        set(6, status);
    }
}
