/*
 * This file is generated by jOOQ.
 */
package com.tesis.jooq.tables.records;


import com.tesis.jooq.tables.Devices;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DevicesRecord extends UpdatableRecordImpl<DevicesRecord> implements Record6<Long, Long, Timestamp, Timestamp, String, String> {

    private static final long serialVersionUID = 1249611405;

    /**
     * Setter for <code>public.devices.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.devices.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.devices.physical_id</code>.
     */
    public void setPhysicalId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.devices.physical_id</code>.
     */
    public Long getPhysicalId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.devices.deleted_at</code>.
     */
    public void setDeletedAt(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.devices.deleted_at</code>.
     */
    public Timestamp getDeletedAt() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>public.devices.last_updated</code>.
     */
    public void setLastUpdated(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.devices.last_updated</code>.
     */
    public Timestamp getLastUpdated() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>public.devices.model</code>.
     */
    public void setModel(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.devices.model</code>.
     */
    public String getModel() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.devices.software_version</code>.
     */
    public void setSoftwareVersion(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.devices.software_version</code>.
     */
    public String getSoftwareVersion() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, Long, Timestamp, Timestamp, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, Long, Timestamp, Timestamp, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Devices.DEVICES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return Devices.DEVICES.PHYSICAL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return Devices.DEVICES.DELETED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Devices.DEVICES.LAST_UPDATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Devices.DEVICES.MODEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Devices.DEVICES.SOFTWARE_VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getPhysicalId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getDeletedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getLastUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getModel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getSoftwareVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getPhysicalId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getDeletedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getLastUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getModel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getSoftwareVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DevicesRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DevicesRecord value2(Long value) {
        setPhysicalId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DevicesRecord value3(Timestamp value) {
        setDeletedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DevicesRecord value4(Timestamp value) {
        setLastUpdated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DevicesRecord value5(String value) {
        setModel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DevicesRecord value6(String value) {
        setSoftwareVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DevicesRecord values(Long value1, Long value2, Timestamp value3, Timestamp value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DevicesRecord
     */
    public DevicesRecord() {
        super(Devices.DEVICES);
    }

    /**
     * Create a detached, initialised DevicesRecord
     */
    public DevicesRecord(Long id, Long physicalId, Timestamp deletedAt, Timestamp lastUpdated, String model, String softwareVersion) {
        super(Devices.DEVICES);

        set(0, id);
        set(1, physicalId);
        set(2, deletedAt);
        set(3, lastUpdated);
        set(4, model);
        set(5, softwareVersion);
    }
}
