/*
 * This file is generated by jOOQ.
 */
package com.tesis.jooq.tables.records;


import com.tesis.jooq.tables.SpeedAlerts;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpeedAlertsRecord extends UpdatableRecordImpl<SpeedAlertsRecord> implements Record7<Long, Boolean, Float, Long, Timestamp, Timestamp, Timestamp> {

    private static final long serialVersionUID = -309536829;

    /**
     * Setter for <code>public.speed_alerts.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.speed_alerts.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.speed_alerts.active</code>.
     */
    public void setActive(Boolean value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.speed_alerts.active</code>.
     */
    public Boolean getActive() {
        return (Boolean) get(1);
    }

    /**
     * Setter for <code>public.speed_alerts.speed</code>.
     */
    public void setSpeed(Float value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.speed_alerts.speed</code>.
     */
    public Float getSpeed() {
        return (Float) get(2);
    }

    /**
     * Setter for <code>public.speed_alerts.device_id</code>.
     */
    public void setDeviceId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.speed_alerts.device_id</code>.
     */
    public Long getDeviceId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.speed_alerts.created_at</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.speed_alerts.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>public.speed_alerts.updated_at</code>.
     */
    public void setUpdatedAt(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.speed_alerts.updated_at</code>.
     */
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>public.speed_alerts.activated_at</code>.
     */
    public void setActivatedAt(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.speed_alerts.activated_at</code>.
     */
    public Timestamp getActivatedAt() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, Boolean, Float, Long, Timestamp, Timestamp, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, Boolean, Float, Long, Timestamp, Timestamp, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return SpeedAlerts.SPEED_ALERTS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field2() {
        return SpeedAlerts.SPEED_ALERTS.ACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Float> field3() {
        return SpeedAlerts.SPEED_ALERTS.SPEED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return SpeedAlerts.SPEED_ALERTS.DEVICE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return SpeedAlerts.SPEED_ALERTS.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return SpeedAlerts.SPEED_ALERTS.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return SpeedAlerts.SPEED_ALERTS.ACTIVATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component2() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float component3() {
        return getSpeed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component4() {
        return getDeviceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getActivatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value2() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float value3() {
        return getSpeed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getDeviceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getActivatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpeedAlertsRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpeedAlertsRecord value2(Boolean value) {
        setActive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpeedAlertsRecord value3(Float value) {
        setSpeed(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpeedAlertsRecord value4(Long value) {
        setDeviceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpeedAlertsRecord value5(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpeedAlertsRecord value6(Timestamp value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpeedAlertsRecord value7(Timestamp value) {
        setActivatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpeedAlertsRecord values(Long value1, Boolean value2, Float value3, Long value4, Timestamp value5, Timestamp value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SpeedAlertsRecord
     */
    public SpeedAlertsRecord() {
        super(SpeedAlerts.SPEED_ALERTS);
    }

    /**
     * Create a detached, initialised SpeedAlertsRecord
     */
    public SpeedAlertsRecord(Long id, Boolean active, Float speed, Long deviceId, Timestamp createdAt, Timestamp updatedAt, Timestamp activatedAt) {
        super(SpeedAlerts.SPEED_ALERTS);

        set(0, id);
        set(1, active);
        set(2, speed);
        set(3, deviceId);
        set(4, createdAt);
        set(5, updatedAt);
        set(6, activatedAt);
    }
}
