/*
 * This file is generated by jOOQ.
 */
package com.tesis.jooq.tables.records;


import com.tesis.jooq.tables.SpeedAlerts;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpeedAlertsRecord extends UpdatableRecordImpl<SpeedAlertsRecord> implements Record4<Long, Boolean, Float, Long> {

    private static final long serialVersionUID = -1124788824;

    /**
     * Setter for <code>public.speed_alerts.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.speed_alerts.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.speed_alerts.active</code>.
     */
    public void setActive(Boolean value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.speed_alerts.active</code>.
     */
    public Boolean getActive() {
        return (Boolean) get(1);
    }

    /**
     * Setter for <code>public.speed_alerts.speed</code>.
     */
    public void setSpeed(Float value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.speed_alerts.speed</code>.
     */
    public Float getSpeed() {
        return (Float) get(2);
    }

    /**
     * Setter for <code>public.speed_alerts.device_id</code>.
     */
    public void setDeviceId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.speed_alerts.device_id</code>.
     */
    public Long getDeviceId() {
        return (Long) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, Boolean, Float, Long> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, Boolean, Float, Long> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return SpeedAlerts.SPEED_ALERTS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field2() {
        return SpeedAlerts.SPEED_ALERTS.ACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Float> field3() {
        return SpeedAlerts.SPEED_ALERTS.SPEED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return SpeedAlerts.SPEED_ALERTS.DEVICE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component2() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float component3() {
        return getSpeed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component4() {
        return getDeviceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value2() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float value3() {
        return getSpeed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getDeviceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpeedAlertsRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpeedAlertsRecord value2(Boolean value) {
        setActive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpeedAlertsRecord value3(Float value) {
        setSpeed(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpeedAlertsRecord value4(Long value) {
        setDeviceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpeedAlertsRecord values(Long value1, Boolean value2, Float value3, Long value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SpeedAlertsRecord
     */
    public SpeedAlertsRecord() {
        super(SpeedAlerts.SPEED_ALERTS);
    }

    /**
     * Create a detached, initialised SpeedAlertsRecord
     */
    public SpeedAlertsRecord(Long id, Boolean active, Float speed, Long deviceId) {
        super(SpeedAlerts.SPEED_ALERTS);

        set(0, id);
        set(1, active);
        set(2, speed);
        set(3, deviceId);
    }
}
