/*
 * This file is generated by jOOQ.
 */
package com.tesis.jooq.tables.records;


import com.tesis.jooq.tables.Trackings;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TrackingsRecord extends UpdatableRecordImpl<TrackingsRecord> implements Record8<Long, Long, Float, Float, Float, Integer, Integer, LocalDateTime> {

    private static final long serialVersionUID = -1928232454;

    /**
     * Setter for <code>public.trackings.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.trackings.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.trackings.device_id</code>.
     */
    public void setDeviceId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.trackings.device_id</code>.
     */
    public Long getDeviceId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.trackings.lat</code>.
     */
    public void setLat(Float value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.trackings.lat</code>.
     */
    public Float getLat() {
        return (Float) get(2);
    }

    /**
     * Setter for <code>public.trackings.lng</code>.
     */
    public void setLng(Float value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.trackings.lng</code>.
     */
    public Float getLng() {
        return (Float) get(3);
    }

    /**
     * Setter for <code>public.trackings.speed</code>.
     */
    public void setSpeed(Float value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.trackings.speed</code>.
     */
    public Float getSpeed() {
        return (Float) get(4);
    }

    /**
     * Setter for <code>public.trackings.sat</code>.
     */
    public void setSat(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.trackings.sat</code>.
     */
    public Integer getSat() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.trackings.hdop</code>.
     */
    public void setHdop(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.trackings.hdop</code>.
     */
    public Integer getHdop() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.trackings.time</code>.
     */
    public void setTime(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.trackings.time</code>.
     */
    public LocalDateTime getTime() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, Long, Float, Float, Float, Integer, Integer, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Long, Long, Float, Float, Float, Integer, Integer, LocalDateTime> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Trackings.TRACKINGS.ID;
    }

    @Override
    public Field<Long> field2() {
        return Trackings.TRACKINGS.DEVICE_ID;
    }

    @Override
    public Field<Float> field3() {
        return Trackings.TRACKINGS.LAT;
    }

    @Override
    public Field<Float> field4() {
        return Trackings.TRACKINGS.LNG;
    }

    @Override
    public Field<Float> field5() {
        return Trackings.TRACKINGS.SPEED;
    }

    @Override
    public Field<Integer> field6() {
        return Trackings.TRACKINGS.SAT;
    }

    @Override
    public Field<Integer> field7() {
        return Trackings.TRACKINGS.HDOP;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return Trackings.TRACKINGS.TIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getDeviceId();
    }

    @Override
    public Float component3() {
        return getLat();
    }

    @Override
    public Float component4() {
        return getLng();
    }

    @Override
    public Float component5() {
        return getSpeed();
    }

    @Override
    public Integer component6() {
        return getSat();
    }

    @Override
    public Integer component7() {
        return getHdop();
    }

    @Override
    public LocalDateTime component8() {
        return getTime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getDeviceId();
    }

    @Override
    public Float value3() {
        return getLat();
    }

    @Override
    public Float value4() {
        return getLng();
    }

    @Override
    public Float value5() {
        return getSpeed();
    }

    @Override
    public Integer value6() {
        return getSat();
    }

    @Override
    public Integer value7() {
        return getHdop();
    }

    @Override
    public LocalDateTime value8() {
        return getTime();
    }

    @Override
    public TrackingsRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public TrackingsRecord value2(Long value) {
        setDeviceId(value);
        return this;
    }

    @Override
    public TrackingsRecord value3(Float value) {
        setLat(value);
        return this;
    }

    @Override
    public TrackingsRecord value4(Float value) {
        setLng(value);
        return this;
    }

    @Override
    public TrackingsRecord value5(Float value) {
        setSpeed(value);
        return this;
    }

    @Override
    public TrackingsRecord value6(Integer value) {
        setSat(value);
        return this;
    }

    @Override
    public TrackingsRecord value7(Integer value) {
        setHdop(value);
        return this;
    }

    @Override
    public TrackingsRecord value8(LocalDateTime value) {
        setTime(value);
        return this;
    }

    @Override
    public TrackingsRecord values(Long value1, Long value2, Float value3, Float value4, Float value5, Integer value6, Integer value7, LocalDateTime value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TrackingsRecord
     */
    public TrackingsRecord() {
        super(Trackings.TRACKINGS);
    }

    /**
     * Create a detached, initialised TrackingsRecord
     */
    public TrackingsRecord(Long id, Long deviceId, Float lat, Float lng, Float speed, Integer sat, Integer hdop, LocalDateTime time) {
        super(Trackings.TRACKINGS);

        set(0, id);
        set(1, deviceId);
        set(2, lat);
        set(3, lng);
        set(4, speed);
        set(5, sat);
        set(6, hdop);
        set(7, time);
    }
}
