/*
 * This file is generated by jOOQ.
 */
package com.tesis.jooq.tables.records;


import com.tesis.jooq.tables.Vehicles;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VehiclesRecord extends UpdatableRecordImpl<VehiclesRecord> implements Record6<Integer, Timestamp, Timestamp, String, String, String> {

    private static final long serialVersionUID = 657923967;

    /**
     * Setter for <code>public.vehicles.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.vehicles.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.vehicles.deleted_at</code>.
     */
    public void setDeletedAt(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.vehicles.deleted_at</code>.
     */
    public Timestamp getDeletedAt() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>public.vehicles.last_updated</code>.
     */
    public void setLastUpdated(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.vehicles.last_updated</code>.
     */
    public Timestamp getLastUpdated() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>public.vehicles.type</code>.
     */
    public void setType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.vehicles.type</code>.
     */
    public String getType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.vehicles.plate</code>.
     */
    public void setPlate(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.vehicles.plate</code>.
     */
    public String getPlate() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.vehicles.model</code>.
     */
    public void setModel(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.vehicles.model</code>.
     */
    public String getModel() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Timestamp, Timestamp, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Timestamp, Timestamp, String, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Vehicles.VEHICLES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return Vehicles.VEHICLES.DELETED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return Vehicles.VEHICLES.LAST_UPDATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Vehicles.VEHICLES.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Vehicles.VEHICLES.PLATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Vehicles.VEHICLES.MODEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component2() {
        return getDeletedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getLastUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getPlate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getModel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getDeletedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getLastUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getPlate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getModel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VehiclesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VehiclesRecord value2(Timestamp value) {
        setDeletedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VehiclesRecord value3(Timestamp value) {
        setLastUpdated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VehiclesRecord value4(String value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VehiclesRecord value5(String value) {
        setPlate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VehiclesRecord value6(String value) {
        setModel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VehiclesRecord values(Integer value1, Timestamp value2, Timestamp value3, String value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VehiclesRecord
     */
    public VehiclesRecord() {
        super(Vehicles.VEHICLES);
    }

    /**
     * Create a detached, initialised VehiclesRecord
     */
    public VehiclesRecord(Integer id, Timestamp deletedAt, Timestamp lastUpdated, String type, String plate, String model) {
        super(Vehicles.VEHICLES);

        set(0, id);
        set(1, deletedAt);
        set(2, lastUpdated);
        set(3, type);
        set(4, plate);
        set(5, model);
    }
}
