/*
 * This file is generated by jOOQ.
 */
package com.tesis.jooq.tables.records;


import com.tesis.jooq.tables.Vehicles;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VehiclesRecord extends UpdatableRecordImpl<VehiclesRecord> implements Record9<Long, String, LocalDateTime, LocalDateTime, Long, Long, String, String, String> {

    private static final long serialVersionUID = -941262196;

    /**
     * Setter for <code>public.vehicles.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.vehicles.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.vehicles.status</code>.
     */
    public void setStatus(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.vehicles.status</code>.
     */
    public String getStatus() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.vehicles.deleted_at</code>.
     */
    public void setDeletedAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.vehicles.deleted_at</code>.
     */
    public LocalDateTime getDeletedAt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.vehicles.last_updated</code>.
     */
    public void setLastUpdated(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.vehicles.last_updated</code>.
     */
    public LocalDateTime getLastUpdated() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.vehicles.user_id</code>.
     */
    public void setUserId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.vehicles.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.vehicles.device_id</code>.
     */
    public void setDeviceId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.vehicles.device_id</code>.
     */
    public Long getDeviceId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.vehicles.plate</code>.
     */
    public void setPlate(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.vehicles.plate</code>.
     */
    public String getPlate() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.vehicles.brand</code>.
     */
    public void setBrand(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.vehicles.brand</code>.
     */
    public String getBrand() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.vehicles.brand_line</code>.
     */
    public void setBrandLine(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.vehicles.brand_line</code>.
     */
    public String getBrandLine() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, String, LocalDateTime, LocalDateTime, Long, Long, String, String, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Long, String, LocalDateTime, LocalDateTime, Long, Long, String, String, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Vehicles.VEHICLES.ID;
    }

    @Override
    public Field<String> field2() {
        return Vehicles.VEHICLES.STATUS;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return Vehicles.VEHICLES.DELETED_AT;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return Vehicles.VEHICLES.LAST_UPDATED;
    }

    @Override
    public Field<Long> field5() {
        return Vehicles.VEHICLES.USER_ID;
    }

    @Override
    public Field<Long> field6() {
        return Vehicles.VEHICLES.DEVICE_ID;
    }

    @Override
    public Field<String> field7() {
        return Vehicles.VEHICLES.PLATE;
    }

    @Override
    public Field<String> field8() {
        return Vehicles.VEHICLES.BRAND;
    }

    @Override
    public Field<String> field9() {
        return Vehicles.VEHICLES.BRAND_LINE;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getStatus();
    }

    @Override
    public LocalDateTime component3() {
        return getDeletedAt();
    }

    @Override
    public LocalDateTime component4() {
        return getLastUpdated();
    }

    @Override
    public Long component5() {
        return getUserId();
    }

    @Override
    public Long component6() {
        return getDeviceId();
    }

    @Override
    public String component7() {
        return getPlate();
    }

    @Override
    public String component8() {
        return getBrand();
    }

    @Override
    public String component9() {
        return getBrandLine();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getStatus();
    }

    @Override
    public LocalDateTime value3() {
        return getDeletedAt();
    }

    @Override
    public LocalDateTime value4() {
        return getLastUpdated();
    }

    @Override
    public Long value5() {
        return getUserId();
    }

    @Override
    public Long value6() {
        return getDeviceId();
    }

    @Override
    public String value7() {
        return getPlate();
    }

    @Override
    public String value8() {
        return getBrand();
    }

    @Override
    public String value9() {
        return getBrandLine();
    }

    @Override
    public VehiclesRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public VehiclesRecord value2(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public VehiclesRecord value3(LocalDateTime value) {
        setDeletedAt(value);
        return this;
    }

    @Override
    public VehiclesRecord value4(LocalDateTime value) {
        setLastUpdated(value);
        return this;
    }

    @Override
    public VehiclesRecord value5(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public VehiclesRecord value6(Long value) {
        setDeviceId(value);
        return this;
    }

    @Override
    public VehiclesRecord value7(String value) {
        setPlate(value);
        return this;
    }

    @Override
    public VehiclesRecord value8(String value) {
        setBrand(value);
        return this;
    }

    @Override
    public VehiclesRecord value9(String value) {
        setBrandLine(value);
        return this;
    }

    @Override
    public VehiclesRecord values(Long value1, String value2, LocalDateTime value3, LocalDateTime value4, Long value5, Long value6, String value7, String value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VehiclesRecord
     */
    public VehiclesRecord() {
        super(Vehicles.VEHICLES);
    }

    /**
     * Create a detached, initialised VehiclesRecord
     */
    public VehiclesRecord(Long id, String status, LocalDateTime deletedAt, LocalDateTime lastUpdated, Long userId, Long deviceId, String plate, String brand, String brandLine) {
        super(Vehicles.VEHICLES);

        set(0, id);
        set(1, status);
        set(2, deletedAt);
        set(3, lastUpdated);
        set(4, userId);
        set(5, deviceId);
        set(6, plate);
        set(7, brand);
        set(8, brandLine);
    }
}
