/*
 * This file is generated by jOOQ.
 */
package com.tesis.jooq.tables;


import com.tesis.jooq.Indexes;
import com.tesis.jooq.Keys;
import com.tesis.jooq.Public;
import com.tesis.jooq.tables.records.RecoveryTokensRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RecoveryTokens extends TableImpl<RecoveryTokensRecord> {

    private static final long serialVersionUID = 614948750;

    /**
     * The reference instance of <code>public.recovery_tokens</code>
     */
    public static final RecoveryTokens RECOVERY_TOKENS = new RecoveryTokens();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RecoveryTokensRecord> getRecordType() {
        return RecoveryTokensRecord.class;
    }

    /**
     * The column <code>public.recovery_tokens.user_id</code>.
     */
    public final TableField<RecoveryTokensRecord, Long> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.recovery_tokens.token</code>.
     */
    public final TableField<RecoveryTokensRecord, String> TOKEN = createField("token", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

    /**
     * The column <code>public.recovery_tokens.expiration_date</code>.
     */
    public final TableField<RecoveryTokensRecord, Timestamp> EXPIRATION_DATE = createField("expiration_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * Create a <code>public.recovery_tokens</code> table reference
     */
    public RecoveryTokens() {
        this(DSL.name("recovery_tokens"), null);
    }

    /**
     * Create an aliased <code>public.recovery_tokens</code> table reference
     */
    public RecoveryTokens(String alias) {
        this(DSL.name(alias), RECOVERY_TOKENS);
    }

    /**
     * Create an aliased <code>public.recovery_tokens</code> table reference
     */
    public RecoveryTokens(Name alias) {
        this(alias, RECOVERY_TOKENS);
    }

    private RecoveryTokens(Name alias, Table<RecoveryTokensRecord> aliased) {
        this(alias, aliased, null);
    }

    private RecoveryTokens(Name alias, Table<RecoveryTokensRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> RecoveryTokens(Table<O> child, ForeignKey<O, RecoveryTokensRecord> key) {
        super(child, key, RECOVERY_TOKENS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.RECOVERY_TOKENS_PKEY, Indexes.RECOVERY_TOKENS_TOKEN_KEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RecoveryTokensRecord> getPrimaryKey() {
        return Keys.RECOVERY_TOKENS_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RecoveryTokensRecord>> getKeys() {
        return Arrays.<UniqueKey<RecoveryTokensRecord>>asList(Keys.RECOVERY_TOKENS_PKEY, Keys.RECOVERY_TOKENS_TOKEN_KEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<RecoveryTokensRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<RecoveryTokensRecord, ?>>asList(Keys.RECOVERY_TOKENS__RECOVERY_TOKENS_USER_ID_FKEY);
    }

    public Users users() {
        return new Users(this, Keys.RECOVERY_TOKENS__RECOVERY_TOKENS_USER_ID_FKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecoveryTokens as(String alias) {
        return new RecoveryTokens(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecoveryTokens as(Name alias) {
        return new RecoveryTokens(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RecoveryTokens rename(String name) {
        return new RecoveryTokens(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RecoveryTokens rename(Name name) {
        return new RecoveryTokens(name, null);
    }
}
