/*
 * This file is generated by jOOQ.
 */
package com.tesis.jooq.tables;


import com.tesis.jooq.Indexes;
import com.tesis.jooq.Keys;
import com.tesis.jooq.Public;
import com.tesis.jooq.tables.records.TrackingsRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Trackings extends TableImpl<TrackingsRecord> {

    private static final long serialVersionUID = 615273798;

    /**
     * The reference instance of <code>public.trackings</code>
     */
    public static final Trackings TRACKINGS = new Trackings();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TrackingsRecord> getRecordType() {
        return TrackingsRecord.class;
    }

    /**
     * The column <code>public.trackings.id</code>.
     */
    public final TableField<TrackingsRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('trakings_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.trackings.device_id</code>.
     */
    public final TableField<TrackingsRecord, Long> DEVICE_ID = createField("device_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.trackings.lat</code>.
     */
    public final TableField<TrackingsRecord, Float> LAT = createField("lat", org.jooq.impl.SQLDataType.REAL.nullable(false), this, "");

    /**
     * The column <code>public.trackings.long</code>.
     */
    public final TableField<TrackingsRecord, Float> LONG = createField("long", org.jooq.impl.SQLDataType.REAL.nullable(false), this, "");

    /**
     * The column <code>public.trackings.sat</code>.
     */
    public final TableField<TrackingsRecord, Integer> SAT = createField("sat", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.trackings.hdop</code>.
     */
    public final TableField<TrackingsRecord, Integer> HDOP = createField("hdop", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.trackings.time</code>.
     */
    public final TableField<TrackingsRecord, Timestamp> TIME = createField("time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * Create a <code>public.trackings</code> table reference
     */
    public Trackings() {
        this(DSL.name("trackings"), null);
    }

    /**
     * Create an aliased <code>public.trackings</code> table reference
     */
    public Trackings(String alias) {
        this(DSL.name(alias), TRACKINGS);
    }

    /**
     * Create an aliased <code>public.trackings</code> table reference
     */
    public Trackings(Name alias) {
        this(alias, TRACKINGS);
    }

    private Trackings(Name alias, Table<TrackingsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Trackings(Name alias, Table<TrackingsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Trackings(Table<O> child, ForeignKey<O, TrackingsRecord> key) {
        super(child, key, TRACKINGS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.TRAKINGS_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TrackingsRecord, Integer> getIdentity() {
        return Keys.IDENTITY_TRACKINGS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TrackingsRecord> getPrimaryKey() {
        return Keys.TRAKINGS_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TrackingsRecord>> getKeys() {
        return Arrays.<UniqueKey<TrackingsRecord>>asList(Keys.TRAKINGS_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<TrackingsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TrackingsRecord, ?>>asList(Keys.TRACKINGS__TRAKINGS_DEVICE_ID_FKEY);
    }

    public Devices devices() {
        return new Devices(this, Keys.TRACKINGS__TRAKINGS_DEVICE_ID_FKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Trackings as(String alias) {
        return new Trackings(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Trackings as(Name alias) {
        return new Trackings(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Trackings rename(String name) {
        return new Trackings(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Trackings rename(Name name) {
        return new Trackings(name, null);
    }
}
