/*
 * This file is generated by jOOQ.
 */
package com.tesis.jooq;


import com.tesis.jooq.tables.Devices;
import com.tesis.jooq.tables.Trakings;
import com.tesis.jooq.tables.Users;
import com.tesis.jooq.tables.Vehicles;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index DEVICES_PKEY = Indexes0.DEVICES_PKEY;
    public static final Index DEVICES_VEHICLE_ID_KEY = Indexes0.DEVICES_VEHICLE_ID_KEY;
    public static final Index TRAKINGS_PKEY = Indexes0.TRAKINGS_PKEY;
    public static final Index USERS_PKEY = Indexes0.USERS_PKEY;
    public static final Index VEHICLES_PKEY = Indexes0.VEHICLES_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index DEVICES_PKEY = Internal.createIndex("devices_pkey", Devices.DEVICES, new OrderField[] { Devices.DEVICES.ID }, true);
        public static Index DEVICES_VEHICLE_ID_KEY = Internal.createIndex("devices_vehicle_id_key", Devices.DEVICES, new OrderField[] { Devices.DEVICES.VEHICLE_ID }, true);
        public static Index TRAKINGS_PKEY = Internal.createIndex("trakings_pkey", Trakings.TRAKINGS, new OrderField[] { Trakings.TRAKINGS.ID }, true);
        public static Index USERS_PKEY = Internal.createIndex("users_pkey", Users.USERS, new OrderField[] { Users.USERS.ID }, true);
        public static Index VEHICLES_PKEY = Internal.createIndex("vehicles_pkey", Vehicles.VEHICLES, new OrderField[] { Vehicles.VEHICLES.ID }, true);
    }
}
