/*
 * This file is generated by jOOQ.
 */
package com.tesis.jooq;


import com.tesis.jooq.tables.AccessTokens;
import com.tesis.jooq.tables.Devices;
import com.tesis.jooq.tables.MovementAlerts;
import com.tesis.jooq.tables.MovementAlertsHistory;
import com.tesis.jooq.tables.SpeedAlerts;
import com.tesis.jooq.tables.SpeedAlertsHistory;
import com.tesis.jooq.tables.Trackings;
import com.tesis.jooq.tables.Users;
import com.tesis.jooq.tables.Vehicles;
import com.tesis.jooq.tables.records.AccessTokensRecord;
import com.tesis.jooq.tables.records.DevicesRecord;
import com.tesis.jooq.tables.records.MovementAlertsHistoryRecord;
import com.tesis.jooq.tables.records.MovementAlertsRecord;
import com.tesis.jooq.tables.records.SpeedAlertsHistoryRecord;
import com.tesis.jooq.tables.records.SpeedAlertsRecord;
import com.tesis.jooq.tables.records.TrackingsRecord;
import com.tesis.jooq.tables.records.UsersRecord;
import com.tesis.jooq.tables.records.VehiclesRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<MovementAlertsRecord, Long> IDENTITY_MOVEMENT_ALERTS = Identities0.IDENTITY_MOVEMENT_ALERTS;
    public static final Identity<SpeedAlertsRecord, Long> IDENTITY_SPEED_ALERTS = Identities0.IDENTITY_SPEED_ALERTS;
    public static final Identity<TrackingsRecord, Long> IDENTITY_TRACKINGS = Identities0.IDENTITY_TRACKINGS;
    public static final Identity<UsersRecord, Long> IDENTITY_USERS = Identities0.IDENTITY_USERS;
    public static final Identity<VehiclesRecord, Long> IDENTITY_VEHICLES = Identities0.IDENTITY_VEHICLES;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AccessTokensRecord> ACCESS_TOKENS_PKEY = UniqueKeys0.ACCESS_TOKENS_PKEY;
    public static final UniqueKey<DevicesRecord> DEVICES_PKEY = UniqueKeys0.DEVICES_PKEY;
    public static final UniqueKey<MovementAlertsRecord> MOVEMENT_ALERTS_PKEY = UniqueKeys0.MOVEMENT_ALERTS_PKEY;
    public static final UniqueKey<MovementAlertsRecord> MOVEMENT_ALERTS_DEVICE_ID_KEY = UniqueKeys0.MOVEMENT_ALERTS_DEVICE_ID_KEY;
    public static final UniqueKey<MovementAlertsHistoryRecord> MOVEMENT_ALERTS_HISTORY_PKEY = UniqueKeys0.MOVEMENT_ALERTS_HISTORY_PKEY;
    public static final UniqueKey<SpeedAlertsRecord> SPEED_ALERTS_PKEY = UniqueKeys0.SPEED_ALERTS_PKEY;
    public static final UniqueKey<SpeedAlertsRecord> SPEED_ALERTS_DEVICE_ID_KEY = UniqueKeys0.SPEED_ALERTS_DEVICE_ID_KEY;
    public static final UniqueKey<SpeedAlertsHistoryRecord> SPEED_ALERTS_HISTORY_PKEY = UniqueKeys0.SPEED_ALERTS_HISTORY_PKEY;
    public static final UniqueKey<TrackingsRecord> TRACKINGS_PKEY = UniqueKeys0.TRACKINGS_PKEY;
    public static final UniqueKey<UsersRecord> USERS_PKEY = UniqueKeys0.USERS_PKEY;
    public static final UniqueKey<UsersRecord> USERS_EMAIL_KEY = UniqueKeys0.USERS_EMAIL_KEY;
    public static final UniqueKey<VehiclesRecord> VEHICLES_PKEY = UniqueKeys0.VEHICLES_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AccessTokensRecord, UsersRecord> ACCESS_TOKENS__ACCESS_TOKENS_USER_ID_FKEY = ForeignKeys0.ACCESS_TOKENS__ACCESS_TOKENS_USER_ID_FKEY;
    public static final ForeignKey<MovementAlertsRecord, DevicesRecord> MOVEMENT_ALERTS__MOVEMENT_ALERTS_DEVICE_ID_FKEY = ForeignKeys0.MOVEMENT_ALERTS__MOVEMENT_ALERTS_DEVICE_ID_FKEY;
    public static final ForeignKey<MovementAlertsHistoryRecord, SpeedAlertsRecord> MOVEMENT_ALERTS_HISTORY__MOVEMENT_ALERTS_HISTORY_ALERT_ID_FKEY = ForeignKeys0.MOVEMENT_ALERTS_HISTORY__MOVEMENT_ALERTS_HISTORY_ALERT_ID_FKEY;
    public static final ForeignKey<SpeedAlertsRecord, DevicesRecord> SPEED_ALERTS__SPEED_ALERTS_DEVICE_ID_FKEY = ForeignKeys0.SPEED_ALERTS__SPEED_ALERTS_DEVICE_ID_FKEY;
    public static final ForeignKey<SpeedAlertsHistoryRecord, SpeedAlertsRecord> SPEED_ALERTS_HISTORY__SPEED_ALERTS_HISTORY_ALERT_ID_FKEY = ForeignKeys0.SPEED_ALERTS_HISTORY__SPEED_ALERTS_HISTORY_ALERT_ID_FKEY;
    public static final ForeignKey<TrackingsRecord, DevicesRecord> TRACKINGS__TRACKINGS_DEVICE_ID_FKEY = ForeignKeys0.TRACKINGS__TRACKINGS_DEVICE_ID_FKEY;
    public static final ForeignKey<VehiclesRecord, UsersRecord> VEHICLES__VEHICLES_USER_ID_FKEY = ForeignKeys0.VEHICLES__VEHICLES_USER_ID_FKEY;
    public static final ForeignKey<VehiclesRecord, DevicesRecord> VEHICLES__VEHICLES_DEVICE_ID_FKEY = ForeignKeys0.VEHICLES__VEHICLES_DEVICE_ID_FKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<MovementAlertsRecord, Long> IDENTITY_MOVEMENT_ALERTS = Internal.createIdentity(MovementAlerts.MOVEMENT_ALERTS, MovementAlerts.MOVEMENT_ALERTS.ID);
        public static Identity<SpeedAlertsRecord, Long> IDENTITY_SPEED_ALERTS = Internal.createIdentity(SpeedAlerts.SPEED_ALERTS, SpeedAlerts.SPEED_ALERTS.ID);
        public static Identity<TrackingsRecord, Long> IDENTITY_TRACKINGS = Internal.createIdentity(Trackings.TRACKINGS, Trackings.TRACKINGS.ID);
        public static Identity<UsersRecord, Long> IDENTITY_USERS = Internal.createIdentity(Users.USERS, Users.USERS.ID);
        public static Identity<VehiclesRecord, Long> IDENTITY_VEHICLES = Internal.createIdentity(Vehicles.VEHICLES, Vehicles.VEHICLES.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<AccessTokensRecord> ACCESS_TOKENS_PKEY = Internal.createUniqueKey(AccessTokens.ACCESS_TOKENS, "access_tokens_pkey", AccessTokens.ACCESS_TOKENS.USER_ID);
        public static final UniqueKey<DevicesRecord> DEVICES_PKEY = Internal.createUniqueKey(Devices.DEVICES, "devices_pkey", Devices.DEVICES.ID);
        public static final UniqueKey<MovementAlertsRecord> MOVEMENT_ALERTS_PKEY = Internal.createUniqueKey(MovementAlerts.MOVEMENT_ALERTS, "movement_alerts_pkey", MovementAlerts.MOVEMENT_ALERTS.ID);
        public static final UniqueKey<MovementAlertsRecord> MOVEMENT_ALERTS_DEVICE_ID_KEY = Internal.createUniqueKey(MovementAlerts.MOVEMENT_ALERTS, "movement_alerts_device_id_key", MovementAlerts.MOVEMENT_ALERTS.DEVICE_ID);
        public static final UniqueKey<MovementAlertsHistoryRecord> MOVEMENT_ALERTS_HISTORY_PKEY = Internal.createUniqueKey(MovementAlertsHistory.MOVEMENT_ALERTS_HISTORY, "movement_alerts_history_pkey", MovementAlertsHistory.MOVEMENT_ALERTS_HISTORY.TIME);
        public static final UniqueKey<SpeedAlertsRecord> SPEED_ALERTS_PKEY = Internal.createUniqueKey(SpeedAlerts.SPEED_ALERTS, "speed_alerts_pkey", SpeedAlerts.SPEED_ALERTS.ID);
        public static final UniqueKey<SpeedAlertsRecord> SPEED_ALERTS_DEVICE_ID_KEY = Internal.createUniqueKey(SpeedAlerts.SPEED_ALERTS, "speed_alerts_device_id_key", SpeedAlerts.SPEED_ALERTS.DEVICE_ID);
        public static final UniqueKey<SpeedAlertsHistoryRecord> SPEED_ALERTS_HISTORY_PKEY = Internal.createUniqueKey(SpeedAlertsHistory.SPEED_ALERTS_HISTORY, "speed_alerts_history_pkey", SpeedAlertsHistory.SPEED_ALERTS_HISTORY.TIME);
        public static final UniqueKey<TrackingsRecord> TRACKINGS_PKEY = Internal.createUniqueKey(Trackings.TRACKINGS, "trackings_pkey", Trackings.TRACKINGS.ID);
        public static final UniqueKey<UsersRecord> USERS_PKEY = Internal.createUniqueKey(Users.USERS, "users_pkey", Users.USERS.ID);
        public static final UniqueKey<UsersRecord> USERS_EMAIL_KEY = Internal.createUniqueKey(Users.USERS, "users_email_key", Users.USERS.EMAIL);
        public static final UniqueKey<VehiclesRecord> VEHICLES_PKEY = Internal.createUniqueKey(Vehicles.VEHICLES, "vehicles_pkey", Vehicles.VEHICLES.ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<AccessTokensRecord, UsersRecord> ACCESS_TOKENS__ACCESS_TOKENS_USER_ID_FKEY = Internal.createForeignKey(com.tesis.jooq.Keys.USERS_PKEY, AccessTokens.ACCESS_TOKENS, "access_tokens__access_tokens_user_id_fkey", AccessTokens.ACCESS_TOKENS.USER_ID);
        public static final ForeignKey<MovementAlertsRecord, DevicesRecord> MOVEMENT_ALERTS__MOVEMENT_ALERTS_DEVICE_ID_FKEY = Internal.createForeignKey(com.tesis.jooq.Keys.DEVICES_PKEY, MovementAlerts.MOVEMENT_ALERTS, "movement_alerts__movement_alerts_device_id_fkey", MovementAlerts.MOVEMENT_ALERTS.DEVICE_ID);
        public static final ForeignKey<MovementAlertsHistoryRecord, SpeedAlertsRecord> MOVEMENT_ALERTS_HISTORY__MOVEMENT_ALERTS_HISTORY_ALERT_ID_FKEY = Internal.createForeignKey(com.tesis.jooq.Keys.SPEED_ALERTS_PKEY, MovementAlertsHistory.MOVEMENT_ALERTS_HISTORY, "movement_alerts_history__movement_alerts_history_alert_id_fkey", MovementAlertsHistory.MOVEMENT_ALERTS_HISTORY.ALERT_ID);
        public static final ForeignKey<SpeedAlertsRecord, DevicesRecord> SPEED_ALERTS__SPEED_ALERTS_DEVICE_ID_FKEY = Internal.createForeignKey(com.tesis.jooq.Keys.DEVICES_PKEY, SpeedAlerts.SPEED_ALERTS, "speed_alerts__speed_alerts_device_id_fkey", SpeedAlerts.SPEED_ALERTS.DEVICE_ID);
        public static final ForeignKey<SpeedAlertsHistoryRecord, SpeedAlertsRecord> SPEED_ALERTS_HISTORY__SPEED_ALERTS_HISTORY_ALERT_ID_FKEY = Internal.createForeignKey(com.tesis.jooq.Keys.SPEED_ALERTS_PKEY, SpeedAlertsHistory.SPEED_ALERTS_HISTORY, "speed_alerts_history__speed_alerts_history_alert_id_fkey", SpeedAlertsHistory.SPEED_ALERTS_HISTORY.ALERT_ID);
        public static final ForeignKey<TrackingsRecord, DevicesRecord> TRACKINGS__TRACKINGS_DEVICE_ID_FKEY = Internal.createForeignKey(com.tesis.jooq.Keys.DEVICES_PKEY, Trackings.TRACKINGS, "trackings__trackings_device_id_fkey", Trackings.TRACKINGS.DEVICE_ID);
        public static final ForeignKey<VehiclesRecord, UsersRecord> VEHICLES__VEHICLES_USER_ID_FKEY = Internal.createForeignKey(com.tesis.jooq.Keys.USERS_PKEY, Vehicles.VEHICLES, "vehicles__vehicles_user_id_fkey", Vehicles.VEHICLES.USER_ID);
        public static final ForeignKey<VehiclesRecord, DevicesRecord> VEHICLES__VEHICLES_DEVICE_ID_FKEY = Internal.createForeignKey(com.tesis.jooq.Keys.DEVICES_PKEY, Vehicles.VEHICLES, "vehicles__vehicles_device_id_fkey", Vehicles.VEHICLES.DEVICE_ID);
    }
}
