/*
 * This file is generated by jOOQ.
 */
package com.tesis.jooq;


import com.tesis.jooq.tables.AccessTokens;
import com.tesis.jooq.tables.AdminAccessTokens;
import com.tesis.jooq.tables.AdminRecoveryTokens;
import com.tesis.jooq.tables.AdminUsers;
import com.tesis.jooq.tables.BrandLines;
import com.tesis.jooq.tables.Brands;
import com.tesis.jooq.tables.Devices;
import com.tesis.jooq.tables.MovementAlerts;
import com.tesis.jooq.tables.MovementAlertsHistory;
import com.tesis.jooq.tables.RecoveryTokens;
import com.tesis.jooq.tables.SpeedAlerts;
import com.tesis.jooq.tables.SpeedAlertsHistory;
import com.tesis.jooq.tables.Trackings;
import com.tesis.jooq.tables.Users;
import com.tesis.jooq.tables.Vehicles;
import com.tesis.jooq.tables.records.AccessTokensRecord;
import com.tesis.jooq.tables.records.AdminAccessTokensRecord;
import com.tesis.jooq.tables.records.AdminRecoveryTokensRecord;
import com.tesis.jooq.tables.records.AdminUsersRecord;
import com.tesis.jooq.tables.records.BrandLinesRecord;
import com.tesis.jooq.tables.records.BrandsRecord;
import com.tesis.jooq.tables.records.DevicesRecord;
import com.tesis.jooq.tables.records.MovementAlertsHistoryRecord;
import com.tesis.jooq.tables.records.MovementAlertsRecord;
import com.tesis.jooq.tables.records.RecoveryTokensRecord;
import com.tesis.jooq.tables.records.SpeedAlertsHistoryRecord;
import com.tesis.jooq.tables.records.SpeedAlertsRecord;
import com.tesis.jooq.tables.records.TrackingsRecord;
import com.tesis.jooq.tables.records.UsersRecord;
import com.tesis.jooq.tables.records.VehiclesRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<AdminUsersRecord, Long> IDENTITY_ADMIN_USERS = Identities0.IDENTITY_ADMIN_USERS;
    public static final Identity<BrandLinesRecord, Long> IDENTITY_BRAND_LINES = Identities0.IDENTITY_BRAND_LINES;
    public static final Identity<BrandsRecord, Long> IDENTITY_BRANDS = Identities0.IDENTITY_BRANDS;
    public static final Identity<DevicesRecord, Long> IDENTITY_DEVICES = Identities0.IDENTITY_DEVICES;
    public static final Identity<MovementAlertsRecord, Long> IDENTITY_MOVEMENT_ALERTS = Identities0.IDENTITY_MOVEMENT_ALERTS;
    public static final Identity<SpeedAlertsRecord, Long> IDENTITY_SPEED_ALERTS = Identities0.IDENTITY_SPEED_ALERTS;
    public static final Identity<TrackingsRecord, Long> IDENTITY_TRACKINGS = Identities0.IDENTITY_TRACKINGS;
    public static final Identity<UsersRecord, Long> IDENTITY_USERS = Identities0.IDENTITY_USERS;
    public static final Identity<VehiclesRecord, Long> IDENTITY_VEHICLES = Identities0.IDENTITY_VEHICLES;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AccessTokensRecord> ACCESS_TOKENS_PKEY = UniqueKeys0.ACCESS_TOKENS_PKEY;
    public static final UniqueKey<AdminAccessTokensRecord> ADMIN_ACCESS_TOKENS_PKEY = UniqueKeys0.ADMIN_ACCESS_TOKENS_PKEY;
    public static final UniqueKey<AdminRecoveryTokensRecord> ADMIN_RECOVERY_TOKENS_PKEY = UniqueKeys0.ADMIN_RECOVERY_TOKENS_PKEY;
    public static final UniqueKey<AdminRecoveryTokensRecord> ADMIN_RECOVERY_TOKENS_TOKEN_KEY = UniqueKeys0.ADMIN_RECOVERY_TOKENS_TOKEN_KEY;
    public static final UniqueKey<AdminUsersRecord> ADMIN_USERS_PKEY = UniqueKeys0.ADMIN_USERS_PKEY;
    public static final UniqueKey<AdminUsersRecord> ADMIN_USERS_EMAIL_KEY = UniqueKeys0.ADMIN_USERS_EMAIL_KEY;
    public static final UniqueKey<BrandLinesRecord> BRAND_LINES_PKEY = UniqueKeys0.BRAND_LINES_PKEY;
    public static final UniqueKey<BrandsRecord> BRANDS_PKEY = UniqueKeys0.BRANDS_PKEY;
    public static final UniqueKey<DevicesRecord> DEVICES_PKEY = UniqueKeys0.DEVICES_PKEY;
    public static final UniqueKey<DevicesRecord> DEVICES_PHYSICAL_ID_DELETED_AT_KEY = UniqueKeys0.DEVICES_PHYSICAL_ID_DELETED_AT_KEY;
    public static final UniqueKey<MovementAlertsRecord> MOVEMENT_ALERTS_PKEY = UniqueKeys0.MOVEMENT_ALERTS_PKEY;
    public static final UniqueKey<MovementAlertsRecord> MOVEMENT_ALERTS_DEVICE_ID_KEY = UniqueKeys0.MOVEMENT_ALERTS_DEVICE_ID_KEY;
    public static final UniqueKey<MovementAlertsHistoryRecord> MOVEMENT_ALERTS_HISTORY_PKEY = UniqueKeys0.MOVEMENT_ALERTS_HISTORY_PKEY;
    public static final UniqueKey<RecoveryTokensRecord> RECOVERY_TOKENS_PKEY = UniqueKeys0.RECOVERY_TOKENS_PKEY;
    public static final UniqueKey<RecoveryTokensRecord> RECOVERY_TOKENS_TOKEN_KEY = UniqueKeys0.RECOVERY_TOKENS_TOKEN_KEY;
    public static final UniqueKey<SpeedAlertsRecord> SPEED_ALERTS_PKEY = UniqueKeys0.SPEED_ALERTS_PKEY;
    public static final UniqueKey<SpeedAlertsRecord> SPEED_ALERTS_DEVICE_ID_KEY = UniqueKeys0.SPEED_ALERTS_DEVICE_ID_KEY;
    public static final UniqueKey<SpeedAlertsHistoryRecord> SPEED_ALERTS_HISTORY_PKEY = UniqueKeys0.SPEED_ALERTS_HISTORY_PKEY;
    public static final UniqueKey<TrackingsRecord> TRACKINGS_PKEY = UniqueKeys0.TRACKINGS_PKEY;
    public static final UniqueKey<UsersRecord> USERS_PKEY = UniqueKeys0.USERS_PKEY;
    public static final UniqueKey<UsersRecord> USERS_EMAIL_KEY = UniqueKeys0.USERS_EMAIL_KEY;
    public static final UniqueKey<VehiclesRecord> VEHICLES_PKEY = UniqueKeys0.VEHICLES_PKEY;
    public static final UniqueKey<VehiclesRecord> VEHICLES_DEVICE_ID_KEY = UniqueKeys0.VEHICLES_DEVICE_ID_KEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AccessTokensRecord, UsersRecord> ACCESS_TOKENS__ACCESS_TOKENS_USER_ID_FKEY = ForeignKeys0.ACCESS_TOKENS__ACCESS_TOKENS_USER_ID_FKEY;
    public static final ForeignKey<AdminAccessTokensRecord, AdminUsersRecord> ADMIN_ACCESS_TOKENS__ADMIN_ACCESS_TOKENS_USER_ID_FKEY = ForeignKeys0.ADMIN_ACCESS_TOKENS__ADMIN_ACCESS_TOKENS_USER_ID_FKEY;
    public static final ForeignKey<AdminRecoveryTokensRecord, AdminUsersRecord> ADMIN_RECOVERY_TOKENS__ADMIN_RECOVERY_TOKENS_USER_ID_FKEY = ForeignKeys0.ADMIN_RECOVERY_TOKENS__ADMIN_RECOVERY_TOKENS_USER_ID_FKEY;
    public static final ForeignKey<BrandLinesRecord, BrandsRecord> BRAND_LINES__BRAND_LINES_BRAND_ID_FKEY = ForeignKeys0.BRAND_LINES__BRAND_LINES_BRAND_ID_FKEY;
    public static final ForeignKey<MovementAlertsRecord, DevicesRecord> MOVEMENT_ALERTS__MOVEMENT_ALERTS_DEVICE_ID_FKEY = ForeignKeys0.MOVEMENT_ALERTS__MOVEMENT_ALERTS_DEVICE_ID_FKEY;
    public static final ForeignKey<MovementAlertsHistoryRecord, MovementAlertsRecord> MOVEMENT_ALERTS_HISTORY__MOVEMENT_ALERTS_HISTORY_ALERT_ID_FKEY = ForeignKeys0.MOVEMENT_ALERTS_HISTORY__MOVEMENT_ALERTS_HISTORY_ALERT_ID_FKEY;
    public static final ForeignKey<RecoveryTokensRecord, UsersRecord> RECOVERY_TOKENS__RECOVERY_TOKENS_USER_ID_FKEY = ForeignKeys0.RECOVERY_TOKENS__RECOVERY_TOKENS_USER_ID_FKEY;
    public static final ForeignKey<SpeedAlertsRecord, DevicesRecord> SPEED_ALERTS__SPEED_ALERTS_DEVICE_ID_FKEY = ForeignKeys0.SPEED_ALERTS__SPEED_ALERTS_DEVICE_ID_FKEY;
    public static final ForeignKey<SpeedAlertsHistoryRecord, SpeedAlertsRecord> SPEED_ALERTS_HISTORY__SPEED_ALERTS_HISTORY_ALERT_ID_FKEY = ForeignKeys0.SPEED_ALERTS_HISTORY__SPEED_ALERTS_HISTORY_ALERT_ID_FKEY;
    public static final ForeignKey<TrackingsRecord, DevicesRecord> TRACKINGS__TRACKINGS_DEVICE_ID_FKEY = ForeignKeys0.TRACKINGS__TRACKINGS_DEVICE_ID_FKEY;
    public static final ForeignKey<VehiclesRecord, UsersRecord> VEHICLES__VEHICLES_USER_ID_FKEY = ForeignKeys0.VEHICLES__VEHICLES_USER_ID_FKEY;
    public static final ForeignKey<VehiclesRecord, DevicesRecord> VEHICLES__VEHICLES_DEVICE_ID_FKEY = ForeignKeys0.VEHICLES__VEHICLES_DEVICE_ID_FKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<AdminUsersRecord, Long> IDENTITY_ADMIN_USERS = Internal.createIdentity(AdminUsers.ADMIN_USERS, AdminUsers.ADMIN_USERS.ID);
        public static Identity<BrandLinesRecord, Long> IDENTITY_BRAND_LINES = Internal.createIdentity(BrandLines.BRAND_LINES, BrandLines.BRAND_LINES.ID);
        public static Identity<BrandsRecord, Long> IDENTITY_BRANDS = Internal.createIdentity(Brands.BRANDS, Brands.BRANDS.ID);
        public static Identity<DevicesRecord, Long> IDENTITY_DEVICES = Internal.createIdentity(Devices.DEVICES, Devices.DEVICES.ID);
        public static Identity<MovementAlertsRecord, Long> IDENTITY_MOVEMENT_ALERTS = Internal.createIdentity(MovementAlerts.MOVEMENT_ALERTS, MovementAlerts.MOVEMENT_ALERTS.ID);
        public static Identity<SpeedAlertsRecord, Long> IDENTITY_SPEED_ALERTS = Internal.createIdentity(SpeedAlerts.SPEED_ALERTS, SpeedAlerts.SPEED_ALERTS.ID);
        public static Identity<TrackingsRecord, Long> IDENTITY_TRACKINGS = Internal.createIdentity(Trackings.TRACKINGS, Trackings.TRACKINGS.ID);
        public static Identity<UsersRecord, Long> IDENTITY_USERS = Internal.createIdentity(Users.USERS, Users.USERS.ID);
        public static Identity<VehiclesRecord, Long> IDENTITY_VEHICLES = Internal.createIdentity(Vehicles.VEHICLES, Vehicles.VEHICLES.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<AccessTokensRecord> ACCESS_TOKENS_PKEY = Internal.createUniqueKey(AccessTokens.ACCESS_TOKENS, "access_tokens_pkey", AccessTokens.ACCESS_TOKENS.USER_ID);
        public static final UniqueKey<AdminAccessTokensRecord> ADMIN_ACCESS_TOKENS_PKEY = Internal.createUniqueKey(AdminAccessTokens.ADMIN_ACCESS_TOKENS, "admin_access_tokens_pkey", AdminAccessTokens.ADMIN_ACCESS_TOKENS.USER_ID);
        public static final UniqueKey<AdminRecoveryTokensRecord> ADMIN_RECOVERY_TOKENS_PKEY = Internal.createUniqueKey(AdminRecoveryTokens.ADMIN_RECOVERY_TOKENS, "admin_recovery_tokens_pkey", AdminRecoveryTokens.ADMIN_RECOVERY_TOKENS.USER_ID);
        public static final UniqueKey<AdminRecoveryTokensRecord> ADMIN_RECOVERY_TOKENS_TOKEN_KEY = Internal.createUniqueKey(AdminRecoveryTokens.ADMIN_RECOVERY_TOKENS, "admin_recovery_tokens_token_key", AdminRecoveryTokens.ADMIN_RECOVERY_TOKENS.TOKEN);
        public static final UniqueKey<AdminUsersRecord> ADMIN_USERS_PKEY = Internal.createUniqueKey(AdminUsers.ADMIN_USERS, "admin_users_pkey", AdminUsers.ADMIN_USERS.ID);
        public static final UniqueKey<AdminUsersRecord> ADMIN_USERS_EMAIL_KEY = Internal.createUniqueKey(AdminUsers.ADMIN_USERS, "admin_users_email_key", AdminUsers.ADMIN_USERS.EMAIL);
        public static final UniqueKey<BrandLinesRecord> BRAND_LINES_PKEY = Internal.createUniqueKey(BrandLines.BRAND_LINES, "brand_lines_pkey", BrandLines.BRAND_LINES.ID);
        public static final UniqueKey<BrandsRecord> BRANDS_PKEY = Internal.createUniqueKey(Brands.BRANDS, "brands_pkey", Brands.BRANDS.ID);
        public static final UniqueKey<DevicesRecord> DEVICES_PKEY = Internal.createUniqueKey(Devices.DEVICES, "devices_pkey", Devices.DEVICES.ID);
        public static final UniqueKey<DevicesRecord> DEVICES_PHYSICAL_ID_DELETED_AT_KEY = Internal.createUniqueKey(Devices.DEVICES, "devices_physical_id_deleted_at_key", Devices.DEVICES.PHYSICAL_ID, Devices.DEVICES.DELETED_AT);
        public static final UniqueKey<MovementAlertsRecord> MOVEMENT_ALERTS_PKEY = Internal.createUniqueKey(MovementAlerts.MOVEMENT_ALERTS, "movement_alerts_pkey", MovementAlerts.MOVEMENT_ALERTS.ID);
        public static final UniqueKey<MovementAlertsRecord> MOVEMENT_ALERTS_DEVICE_ID_KEY = Internal.createUniqueKey(MovementAlerts.MOVEMENT_ALERTS, "movement_alerts_device_id_key", MovementAlerts.MOVEMENT_ALERTS.DEVICE_ID);
        public static final UniqueKey<MovementAlertsHistoryRecord> MOVEMENT_ALERTS_HISTORY_PKEY = Internal.createUniqueKey(MovementAlertsHistory.MOVEMENT_ALERTS_HISTORY, "movement_alerts_history_pkey", MovementAlertsHistory.MOVEMENT_ALERTS_HISTORY.TIME);
        public static final UniqueKey<RecoveryTokensRecord> RECOVERY_TOKENS_PKEY = Internal.createUniqueKey(RecoveryTokens.RECOVERY_TOKENS, "recovery_tokens_pkey", RecoveryTokens.RECOVERY_TOKENS.USER_ID);
        public static final UniqueKey<RecoveryTokensRecord> RECOVERY_TOKENS_TOKEN_KEY = Internal.createUniqueKey(RecoveryTokens.RECOVERY_TOKENS, "recovery_tokens_token_key", RecoveryTokens.RECOVERY_TOKENS.TOKEN);
        public static final UniqueKey<SpeedAlertsRecord> SPEED_ALERTS_PKEY = Internal.createUniqueKey(SpeedAlerts.SPEED_ALERTS, "speed_alerts_pkey", SpeedAlerts.SPEED_ALERTS.ID);
        public static final UniqueKey<SpeedAlertsRecord> SPEED_ALERTS_DEVICE_ID_KEY = Internal.createUniqueKey(SpeedAlerts.SPEED_ALERTS, "speed_alerts_device_id_key", SpeedAlerts.SPEED_ALERTS.DEVICE_ID);
        public static final UniqueKey<SpeedAlertsHistoryRecord> SPEED_ALERTS_HISTORY_PKEY = Internal.createUniqueKey(SpeedAlertsHistory.SPEED_ALERTS_HISTORY, "speed_alerts_history_pkey", SpeedAlertsHistory.SPEED_ALERTS_HISTORY.TIME);
        public static final UniqueKey<TrackingsRecord> TRACKINGS_PKEY = Internal.createUniqueKey(Trackings.TRACKINGS, "trackings_pkey", Trackings.TRACKINGS.ID);
        public static final UniqueKey<UsersRecord> USERS_PKEY = Internal.createUniqueKey(Users.USERS, "users_pkey", Users.USERS.ID);
        public static final UniqueKey<UsersRecord> USERS_EMAIL_KEY = Internal.createUniqueKey(Users.USERS, "users_email_key", Users.USERS.EMAIL);
        public static final UniqueKey<VehiclesRecord> VEHICLES_PKEY = Internal.createUniqueKey(Vehicles.VEHICLES, "vehicles_pkey", Vehicles.VEHICLES.ID);
        public static final UniqueKey<VehiclesRecord> VEHICLES_DEVICE_ID_KEY = Internal.createUniqueKey(Vehicles.VEHICLES, "vehicles_device_id_key", Vehicles.VEHICLES.DEVICE_ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<AccessTokensRecord, UsersRecord> ACCESS_TOKENS__ACCESS_TOKENS_USER_ID_FKEY = Internal.createForeignKey(com.tesis.jooq.Keys.USERS_PKEY, AccessTokens.ACCESS_TOKENS, "access_tokens__access_tokens_user_id_fkey", AccessTokens.ACCESS_TOKENS.USER_ID);
        public static final ForeignKey<AdminAccessTokensRecord, AdminUsersRecord> ADMIN_ACCESS_TOKENS__ADMIN_ACCESS_TOKENS_USER_ID_FKEY = Internal.createForeignKey(com.tesis.jooq.Keys.ADMIN_USERS_PKEY, AdminAccessTokens.ADMIN_ACCESS_TOKENS, "admin_access_tokens__admin_access_tokens_user_id_fkey", AdminAccessTokens.ADMIN_ACCESS_TOKENS.USER_ID);
        public static final ForeignKey<AdminRecoveryTokensRecord, AdminUsersRecord> ADMIN_RECOVERY_TOKENS__ADMIN_RECOVERY_TOKENS_USER_ID_FKEY = Internal.createForeignKey(com.tesis.jooq.Keys.ADMIN_USERS_PKEY, AdminRecoveryTokens.ADMIN_RECOVERY_TOKENS, "admin_recovery_tokens__admin_recovery_tokens_user_id_fkey", AdminRecoveryTokens.ADMIN_RECOVERY_TOKENS.USER_ID);
        public static final ForeignKey<BrandLinesRecord, BrandsRecord> BRAND_LINES__BRAND_LINES_BRAND_ID_FKEY = Internal.createForeignKey(com.tesis.jooq.Keys.BRANDS_PKEY, BrandLines.BRAND_LINES, "brand_lines__brand_lines_brand_id_fkey", BrandLines.BRAND_LINES.BRAND_ID);
        public static final ForeignKey<MovementAlertsRecord, DevicesRecord> MOVEMENT_ALERTS__MOVEMENT_ALERTS_DEVICE_ID_FKEY = Internal.createForeignKey(com.tesis.jooq.Keys.DEVICES_PKEY, MovementAlerts.MOVEMENT_ALERTS, "movement_alerts__movement_alerts_device_id_fkey", MovementAlerts.MOVEMENT_ALERTS.DEVICE_ID);
        public static final ForeignKey<MovementAlertsHistoryRecord, MovementAlertsRecord> MOVEMENT_ALERTS_HISTORY__MOVEMENT_ALERTS_HISTORY_ALERT_ID_FKEY = Internal.createForeignKey(com.tesis.jooq.Keys.MOVEMENT_ALERTS_PKEY, MovementAlertsHistory.MOVEMENT_ALERTS_HISTORY, "movement_alerts_history__movement_alerts_history_alert_id_fkey", MovementAlertsHistory.MOVEMENT_ALERTS_HISTORY.ALERT_ID);
        public static final ForeignKey<RecoveryTokensRecord, UsersRecord> RECOVERY_TOKENS__RECOVERY_TOKENS_USER_ID_FKEY = Internal.createForeignKey(com.tesis.jooq.Keys.USERS_PKEY, RecoveryTokens.RECOVERY_TOKENS, "recovery_tokens__recovery_tokens_user_id_fkey", RecoveryTokens.RECOVERY_TOKENS.USER_ID);
        public static final ForeignKey<SpeedAlertsRecord, DevicesRecord> SPEED_ALERTS__SPEED_ALERTS_DEVICE_ID_FKEY = Internal.createForeignKey(com.tesis.jooq.Keys.DEVICES_PKEY, SpeedAlerts.SPEED_ALERTS, "speed_alerts__speed_alerts_device_id_fkey", SpeedAlerts.SPEED_ALERTS.DEVICE_ID);
        public static final ForeignKey<SpeedAlertsHistoryRecord, SpeedAlertsRecord> SPEED_ALERTS_HISTORY__SPEED_ALERTS_HISTORY_ALERT_ID_FKEY = Internal.createForeignKey(com.tesis.jooq.Keys.SPEED_ALERTS_PKEY, SpeedAlertsHistory.SPEED_ALERTS_HISTORY, "speed_alerts_history__speed_alerts_history_alert_id_fkey", SpeedAlertsHistory.SPEED_ALERTS_HISTORY.ALERT_ID);
        public static final ForeignKey<TrackingsRecord, DevicesRecord> TRACKINGS__TRACKINGS_DEVICE_ID_FKEY = Internal.createForeignKey(com.tesis.jooq.Keys.DEVICES_PKEY, Trackings.TRACKINGS, "trackings__trackings_device_id_fkey", Trackings.TRACKINGS.DEVICE_ID);
        public static final ForeignKey<VehiclesRecord, UsersRecord> VEHICLES__VEHICLES_USER_ID_FKEY = Internal.createForeignKey(com.tesis.jooq.Keys.USERS_PKEY, Vehicles.VEHICLES, "vehicles__vehicles_user_id_fkey", Vehicles.VEHICLES.USER_ID);
        public static final ForeignKey<VehiclesRecord, DevicesRecord> VEHICLES__VEHICLES_DEVICE_ID_FKEY = Internal.createForeignKey(com.tesis.jooq.Keys.DEVICES_PKEY, Vehicles.VEHICLES, "vehicles__vehicles_device_id_fkey", Vehicles.VEHICLES.DEVICE_ID);
    }
}
