/*
 * This file is generated by jOOQ.
 */
package com.tesis.jooq;


import com.tesis.jooq.tables.Devices;
import com.tesis.jooq.tables.Trakings;
import com.tesis.jooq.tables.Users;
import com.tesis.jooq.tables.Vehicles;
import com.tesis.jooq.tables.records.DevicesRecord;
import com.tesis.jooq.tables.records.TrakingsRecord;
import com.tesis.jooq.tables.records.UsersRecord;
import com.tesis.jooq.tables.records.VehiclesRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<TrakingsRecord, Integer> IDENTITY_TRAKINGS = Identities0.IDENTITY_TRAKINGS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DevicesRecord> DEVICES_PKEY = UniqueKeys0.DEVICES_PKEY;
    public static final UniqueKey<DevicesRecord> DEVICES_VEHICLE_ID_KEY = UniqueKeys0.DEVICES_VEHICLE_ID_KEY;
    public static final UniqueKey<TrakingsRecord> TRAKINGS_PKEY = UniqueKeys0.TRAKINGS_PKEY;
    public static final UniqueKey<UsersRecord> USERS_PKEY = UniqueKeys0.USERS_PKEY;
    public static final UniqueKey<VehiclesRecord> VEHICLES_PKEY = UniqueKeys0.VEHICLES_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<DevicesRecord, UsersRecord> DEVICES__DEVICES_USER_ID_FKEY = ForeignKeys0.DEVICES__DEVICES_USER_ID_FKEY;
    public static final ForeignKey<DevicesRecord, VehiclesRecord> DEVICES__DEVICES_VEHICLE_ID_FKEY = ForeignKeys0.DEVICES__DEVICES_VEHICLE_ID_FKEY;
    public static final ForeignKey<TrakingsRecord, DevicesRecord> TRAKINGS__TRAKINGS_DEVICE_ID_FKEY = ForeignKeys0.TRAKINGS__TRAKINGS_DEVICE_ID_FKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<TrakingsRecord, Integer> IDENTITY_TRAKINGS = Internal.createIdentity(Trakings.TRAKINGS, Trakings.TRAKINGS.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<DevicesRecord> DEVICES_PKEY = Internal.createUniqueKey(Devices.DEVICES, "devices_pkey", Devices.DEVICES.ID);
        public static final UniqueKey<DevicesRecord> DEVICES_VEHICLE_ID_KEY = Internal.createUniqueKey(Devices.DEVICES, "devices_vehicle_id_key", Devices.DEVICES.VEHICLE_ID);
        public static final UniqueKey<TrakingsRecord> TRAKINGS_PKEY = Internal.createUniqueKey(Trakings.TRAKINGS, "trakings_pkey", Trakings.TRAKINGS.ID);
        public static final UniqueKey<UsersRecord> USERS_PKEY = Internal.createUniqueKey(Users.USERS, "users_pkey", Users.USERS.ID);
        public static final UniqueKey<VehiclesRecord> VEHICLES_PKEY = Internal.createUniqueKey(Vehicles.VEHICLES, "vehicles_pkey", Vehicles.VEHICLES.ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<DevicesRecord, UsersRecord> DEVICES__DEVICES_USER_ID_FKEY = Internal.createForeignKey(com.tesis.jooq.Keys.USERS_PKEY, Devices.DEVICES, "devices__devices_user_id_fkey", Devices.DEVICES.USER_ID);
        public static final ForeignKey<DevicesRecord, VehiclesRecord> DEVICES__DEVICES_VEHICLE_ID_FKEY = Internal.createForeignKey(com.tesis.jooq.Keys.VEHICLES_PKEY, Devices.DEVICES, "devices__devices_vehicle_id_fkey", Devices.DEVICES.VEHICLE_ID);
        public static final ForeignKey<TrakingsRecord, DevicesRecord> TRAKINGS__TRAKINGS_DEVICE_ID_FKEY = Internal.createForeignKey(com.tesis.jooq.Keys.DEVICES_PKEY, Trakings.TRAKINGS, "trakings__trakings_device_id_fkey", Trakings.TRAKINGS.DEVICE_ID);
    }
}
