/*
 * This file is generated by jOOQ.
 */
package com.tesis.jooq;


import org.jooq.Sequence;
import org.jooq.impl.Internal;


/**
 * Convenience access to all sequences in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.brand_lines_id_seq</code>
     */
    public static final Sequence<Integer> BRAND_LINES_ID_SEQ = Internal.createSequence("brand_lines_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.brands_id_seq</code>
     */
    public static final Sequence<Integer> BRANDS_ID_SEQ = Internal.createSequence("brands_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.devices_id_seq</code>
     */
    public static final Sequence<Integer> DEVICES_ID_SEQ = Internal.createSequence("devices_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.movement_alerts_id_seq</code>
     */
    public static final Sequence<Integer> MOVEMENT_ALERTS_ID_SEQ = Internal.createSequence("movement_alerts_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.speed_alerts_id_seq</code>
     */
    public static final Sequence<Integer> SPEED_ALERTS_ID_SEQ = Internal.createSequence("speed_alerts_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.trackings_id_seq</code>
     */
    public static final Sequence<Integer> TRACKINGS_ID_SEQ = Internal.createSequence("trackings_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.vehicles_id_seq</code>
     */
    public static final Sequence<Integer> VEHICLES_ID_SEQ = Internal.createSequence("vehicles_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);
}
