/*
 * This file is generated by jOOQ.
 */
package com.tesis.jooq;


import com.tesis.jooq.tables.BrandLines;
import com.tesis.jooq.tables.Brands;
import com.tesis.jooq.tables.Devices;
import com.tesis.jooq.tables.MovementAlerts;
import com.tesis.jooq.tables.MovementAlertsHistory;
import com.tesis.jooq.tables.SpeedAlerts;
import com.tesis.jooq.tables.SpeedAlertsHistory;
import com.tesis.jooq.tables.Trackings;
import com.tesis.jooq.tables.Vehicles;


/**
 * Convenience access to all tables in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.brand_lines</code>.
     */
    public static final BrandLines BRAND_LINES = BrandLines.BRAND_LINES;

    /**
     * The table <code>public.brands</code>.
     */
    public static final Brands BRANDS = Brands.BRANDS;

    /**
     * The table <code>public.devices</code>.
     */
    public static final Devices DEVICES = Devices.DEVICES;

    /**
     * The table <code>public.movement_alerts</code>.
     */
    public static final MovementAlerts MOVEMENT_ALERTS = MovementAlerts.MOVEMENT_ALERTS;

    /**
     * The table <code>public.movement_alerts_history</code>.
     */
    public static final MovementAlertsHistory MOVEMENT_ALERTS_HISTORY = MovementAlertsHistory.MOVEMENT_ALERTS_HISTORY;

    /**
     * The table <code>public.speed_alerts</code>.
     */
    public static final SpeedAlerts SPEED_ALERTS = SpeedAlerts.SPEED_ALERTS;

    /**
     * The table <code>public.speed_alerts_history</code>.
     */
    public static final SpeedAlertsHistory SPEED_ALERTS_HISTORY = SpeedAlertsHistory.SPEED_ALERTS_HISTORY;

    /**
     * The table <code>public.trackings</code>.
     */
    public static final Trackings TRACKINGS = Trackings.TRACKINGS;

    /**
     * The table <code>public.vehicles</code>.
     */
    public static final Vehicles VEHICLES = Vehicles.VEHICLES;
}
